CREATE PROCEDURE [DataSync].[CD_Facebook_Ads_Publisher_Platform_dss_insert_86428056-fea2-4062-8e10-5f42d853c559]
	@P_1 DateTime,
	@P_2 DateTime,
	@P_3 NVarChar(255),
	@P_4 Date,
	@P_5 BigInt,
	@P_6 BigInt,
	@P_7 BigInt,
	@P_8 Decimal(20,4),
	@P_9 BigInt,
	@P_10 BigInt,
	@P_11 NVarChar(max),
	@P_12 BigInt,
	@P_13 BigInt,
	@P_14 Decimal(20,4),
	@P_15 BigInt,
	@P_16 Decimal(20,4),
	@P_17 BigInt,
	@P_18 Decimal(20,4),
	@P_19 NVarChar(200),
	@P_20 NVarChar(max),
	@P_21 NVarChar(200),
	@P_22 BigInt,
	@P_23 BigInt,
	@P_24 BigInt,
	@P_25 BigInt,
	@P_26 NVarChar(max),
	@P_27 BigInt,
	@P_28 BigInt,
	@P_29 NVarChar(max),
	@P_30 BigInt,
	@P_31 BigInt,
	@P_32 BigInt,
	@P_33 Date,
	@P_34 NVarChar(max),
	@P_35 BigInt,
	@P_36 DateTime,
	@P_37 NVarChar(max),
	@P_38 NVarChar(max),
	@P_39 NVarChar(max),
	@P_40 NVarChar(max),
	@P_41 DateTime,
	@P_42 Decimal(20,4),
	@P_43 NVarChar(max),
	@P_44 NVarChar(max),
	@P_45 NVarChar(max),
	@P_46 NVarChar(max),
	@P_47 NVarChar(max),
	@P_48 NVarChar(max),
	@P_49 BigInt,
	@P_50 BigInt,
	@P_51 BigInt,
	@P_52 NVarChar(max),
	@P_53 BigInt,
	@P_54 NVarChar(max),
	@P_55 NVarChar(max),
	@P_56 BigInt,
	@P_57 Decimal(20,4),
	@P_58 NVarChar(max),
	@P_59 BigInt,
	@P_60 BigInt,
	@P_61 Decimal(20,4),
	@P_62 NVarChar(max),
	@P_63 NVarChar(max),
	@P_64 NVarChar(max),
	@P_65 NVarChar(max),
	@P_66 NVarChar(max),
	@P_67 NVarChar(max),
	@sync_row_count Int OUTPUT
AS
BEGIN
SET @sync_row_count = 0; IF (NOT EXISTS (SELECT * FROM [dbo].[CD_Facebook_Ads_Publisher_Platform] WHERE [campaign_id] = @P_5 AND [ad_id] = @P_9 AND [adset_id] = @P_13 AND [publisher_platform_pp] = @P_19 AND [platform_position_pp] = @P_21 AND [account_id] = @P_31 AND [date_start] = @P_33)
 AND NOT EXISTS (SELECT * FROM [DataSync].[CD_Facebook_Ads_Publisher_Platform_dss_tracking] WHERE [campaign_id] = @P_5 AND [ad_id] = @P_9 AND [adset_id] = @P_13 AND [publisher_platform_pp] = @P_19 AND [platform_position_pp] = @P_21 AND [account_id] = @P_31 AND [date_start] = @P_33)
)
BEGIN 
INSERT INTO [dbo].[CD_Facebook_Ads_Publisher_Platform]([dt_created], [dt_updated], [dt_filename], [date_stop], [campaign_id], [video_p25_watched_actionsvideo_view], [actionslink_click], [cpm], [ad_id], [actionspost_reaction], [ad_name], [video_p50_watched_actionsvideo_view], [adset_id], [spend], [actionsvideo_view], [cpc], [impressions], [ctr], [publisher_platform_pp], [adset_name], [platform_position_pp], [video_p75_watched_actionsvideo_view], [video_p100_watched_actionsvideo_view], [actionspost_engagement], [video_play_actionsvideo_view], [campaign_name], [actionscomment], [actionspage_engagement], [objective], [actionsonsite_conversionpost_save], [account_id], [clicks], [date_start], [account_name], [actionspost], [campaign_stop_time], [ad_creative_image_url], [ad_creative_title], [ad_creative_thumbnail_url], [ad_creative_body], [campaign_start_time], [conversions], [video_p100_watched_actions], [video_p25_watched_actions], [video_p50_watched_actions], [video_p75_watched_actions], [video_play_actions], [website_purchase_roas], [actionslike], [actionslanding_page_view], [actionsinteractive_component_tap], [actionsphoto_view], [actionsoffsite_conversionfb_pixel_add_to_cart], [actionsadd_to_cart], [actionspurchase], [actionsomni_add_to_cart], [action_valuesoffsite_conversionfb_pixel_purchase], [website_purchase_roasoffsite_conversionfb_pixel_purchase], [actionsomni_purchase], [actionsoffsite_conversionfb_pixel_purchase], [action_valuesomni_purchase], [actionsinitiate_checkout], [actionsomni_initiated_checkout], [actionsoffsite_conversionfb_pixel_initiate_checkout], [actionsoffsite_conversionfb_pixel_complete_registration], [actionsomni_complete_registration], [actionscomplete_registration]) VALUES (@P_1, @P_2, @P_3, @P_4, @P_5, @P_6, @P_7, @P_8, @P_9, @P_10, @P_11, @P_12, @P_13, @P_14, @P_15, @P_16, @P_17, @P_18, @P_19, @P_20, @P_21, @P_22, @P_23, @P_24, @P_25, @P_26, @P_27, @P_28, @P_29, @P_30, @P_31, @P_32, @P_33, @P_34, @P_35, @P_36, @P_37, @P_38, @P_39, @P_40, @P_41, @P_42, @P_43, @P_44, @P_45, @P_46, @P_47, @P_48, @P_49, @P_50, @P_51, @P_52, @P_53, @P_54, @P_55, @P_56, @P_57, @P_58, @P_59, @P_60, @P_61, @P_62, @P_63, @P_64, @P_65, @P_66, @P_67);  SET @sync_row_count = @@rowcount;  END 
END