CREATE TABLE [dbo].[CD_AMN_Search] (
    [dt_created]                    DATETIME        NULL,
    [dt_updated]                    DATETIME        NULL,
    [dt_filename]                   NVARCHAR (255)  NULL,
    [_currency]                     NVARCHAR (50)   NULL,
    [date]                          DATE            NULL,
    [ad_group_name]                 NVARCHAR (MAX)  NULL,
    [campaign_name]                 NVARCHAR (MAX)  NULL,
    [channel]                       NVARCHAR (MAX)  NULL,
    [keyword]                       NVARCHAR (MAX)  NULL,
    [profile_name]                  NVARCHAR (MAX)  NULL,
    [units_14_day]                  FLOAT (53)      NULL,
    [channel_campaign_id]           BIGINT          NULL,
    [channel_keyword_id]            BIGINT          NULL,
    [channel_ad_group_id]           BIGINT          NULL,
    [channel_account_id]            BIGINT          NULL,
    [account_name]                  NVARCHAR (MAX)  NULL,
    [ad_group_id]                   BIGINT          NULL,
    [adgroup_id_in_kenshoo]         BIGINT          NULL,
    [adgroup_status]                NVARCHAR (MAX)  NULL,
    [bid]                           FLOAT (53)      NULL,
    [campaign_id]                   BIGINT          NULL,
    [campaign_status]               NVARCHAR (MAX)  NULL,
    [channel_account_publisher_id]  BIGINT          NULL,
    [custom_parameter_1]            NVARCHAR (MAX)  NULL,
    [custom_parameter_2]            NVARCHAR (MAX)  NULL,
    [custom_parameter_3]            NVARCHAR (MAX)  NULL,
    [keyword_creation_date]         NVARCHAR (MAX)  NULL,
    [keyword_id]                    BIGINT          NULL,
    [land_url]                      NVARCHAR (MAX)  NULL,
    [last_modified]                 DATETIME        NULL,
    [match_type]                    NVARCHAR (MAX)  NULL,
    [min_bid]                       NVARCHAR (MAX)  NULL,
    [mobile_bid_adjustment]         NVARCHAR (MAX)  NULL,
    [mobile_effective_bid]          NVARCHAR (MAX)  NULL,
    [mobile_url]                    NVARCHAR (MAX)  NULL,
    [network]                       NVARCHAR (MAX)  NULL,
    [profile_currency]              NVARCHAR (MAX)  NULL,
    [profile_id]                    BIGINT          NULL,
    [quality_score]                 NVARCHAR (MAX)  NULL,
    [status]                        NVARCHAR (MAX)  NULL,
    [tracking_id]                   BIGINT          NULL,
    [tracking_template]             NVARCHAR (MAX)  NULL,
    [upgr_url_ind]                  NVARCHAR (MAX)  NULL,
    [avg_cpc]                       NUMERIC (20, 4) NULL,
    [avg_pos]                       BIGINT          NULL,
    [clicks]                        BIGINT          NULL,
    [conv_rate]                     FLOAT (53)      NULL,
    [conversions]                   FLOAT (53)      NULL,
    [cost]                          FLOAT (53)      NULL,
    [costconv]                      FLOAT (53)      NULL,
    [ctr]                           FLOAT (53)      NULL,
    [imp_share]                     FLOAT (53)      NULL,
    [impr_abstop]                   FLOAT (53)      NULL,
    [impr_top]                      FLOAT (53)      NULL,
    [impressions]                   BIGINT          NULL,
    [lost_isrank]                   FLOAT (53)      NULL,
    [potential_impressions]         FLOAT (53)      NULL,
    [profit]                        FLOAT (53)      NULL,
    [rev]                           FLOAT (53)      NULL,
    [revconv]                       FLOAT (53)      NULL,
    [roi]                           FLOAT (53)      NULL,
    [search_abstop_is]              FLOAT (53)      NULL,
    [search_top_is]                 FLOAT (53)      NULL,
    [1_day]                         FLOAT (53)      NULL,
    [1_day_same_sku]                FLOAT (53)      NULL,
    [14_days]                       FLOAT (53)      NULL,
    [14_days_same_sku]              FLOAT (53)      NULL,
    [30_day]                        FLOAT (53)      NULL,
    [30_day_same_sku]               FLOAT (53)      NULL,
    [30_days]                       FLOAT (53)      NULL,
    [30_days_same_sku]              FLOAT (53)      NULL,
    [7_days]                        FLOAT (53)      NULL,
    [7_days_same_sku]               FLOAT (53)      NULL,
    [new_to_brand_order_rate]       FLOAT (53)      NULL,
    [new_to_brand_orders]           FLOAT (53)      NULL,
    [new_to_brand_percentage]       FLOAT (53)      NULL,
    [new_to_brand_units]            FLOAT (53)      NULL,
    [new_to_brand_units_percentage] FLOAT (53)      NULL,
    [page_views]                    FLOAT (53)      NULL,
    [uc_conv]                       FLOAT (53)      NULL,
    [units_1_day]                   FLOAT (53)      NULL,
    [units_30_day]                  FLOAT (53)      NULL,
    [units_7_day]                   FLOAT (53)      NULL,
    [conv]                          FLOAT (53)      NULL,
    [brand__non_brand]              NVARCHAR (MAX)  NULL,
    [keyword_targeting]             NVARCHAR (MAX)  NULL,
    [portfolio_subsets]             NVARCHAR (MAX)  NULL,
    [sov_keyword]                   NVARCHAR (MAX)  NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CD_AMN_Search_dt_filename]
    ON [dbo].[CD_AMN_Search]([dt_filename] ASC);

