CREATE TABLE [dbo].[CD_AMN_Display_All_Metrics] (
    [dt_created]                            DATETIME        NULL,
    [dt_updated]                            DATETIME        NULL,
    [dt_filename]                           NVARCHAR (255)  NULL,
    [date]                                  DATE            NULL,
    [advertiser]                            NVARCHAR (MAX)  NULL,
    [advertiser_id]                         BIGINT          NULL,
    [order]                                 NVARCHAR (MAX)  NULL,
    [order_id]                              BIGINT          NULL,
    [line_item]                             NVARCHAR (MAX)  NULL,
    [line_item_id]                          BIGINT          NULL,
    [creative]                              NVARCHAR (MAX)  NULL,
    [creative_id]                           NVARCHAR (13)   NULL,
    [creative_type]                         NVARCHAR (MAX)  NULL,
    [creative_size]                         NVARCHAR (MAX)  NULL,
    [impressions]                           BIGINT          NULL,
    [viewable_impressions]                  NUMERIC (20, 4) NULL,
    [measurable_impressions]                NUMERIC (20, 4) NULL,
    [measurable_rate]                       NUMERIC (20, 4) NULL,
    [viewability_rate]                      NUMERIC (20, 4) NULL,
    [clickthroughs]                         NUMERIC (20, 4) NULL,
    [ctr]                                   NUMERIC (20, 4) NULL,
    [total_pixel]                           NVARCHAR (MAX)  NULL,
    [total_pixel_views]                     NVARCHAR (MAX)  NULL,
    [total_pixels_clicks]                   NVARCHAR (MAX)  NULL,
    [total_pixel_cvr]                       NVARCHAR (MAX)  NULL,
    [marketing_landing_page]                NVARCHAR (MAX)  NULL,
    [marketing_landing_page_views]          NVARCHAR (MAX)  NULL,
    [marketing_landing_page_clicks]         NVARCHAR (MAX)  NULL,
    [marketing_landing_page_cvr]            NVARCHAR (MAX)  NULL,
    [subscription_page]                     NVARCHAR (MAX)  NULL,
    [subscription_page_views]               NVARCHAR (MAX)  NULL,
    [subscription_page_clicks]              NVARCHAR (MAX)  NULL,
    [subscription_page_cvr]                 NVARCHAR (MAX)  NULL,
    [sign_up_page]                          NVARCHAR (MAX)  NULL,
    [sign_up_page_views]                    NVARCHAR (MAX)  NULL,
    [sign_up_page_clicks]                   NVARCHAR (MAX)  NULL,
    [sign_up_page_cvr]                      NVARCHAR (MAX)  NULL,
    [application]                           NVARCHAR (MAX)  NULL,
    [application_views]                     NVARCHAR (MAX)  NULL,
    [application_clicks]                    NVARCHAR (MAX)  NULL,
    [application_cvr]                       NVARCHAR (MAX)  NULL,
    [game_load]                             NVARCHAR (MAX)  NULL,
    [game_load_views]                       NVARCHAR (MAX)  NULL,
    [game_load_clicks]                      NVARCHAR (MAX)  NULL,
    [game_load_cvr]                         NVARCHAR (MAX)  NULL,
    [widget_load]                           NVARCHAR (MAX)  NULL,
    [widget_load_views]                     NVARCHAR (MAX)  NULL,
    [widget_load_clicks]                    NVARCHAR (MAX)  NULL,
    [widget_load_cvr]                       NVARCHAR (MAX)  NULL,
    [survey_start]                          NVARCHAR (MAX)  NULL,
    [survey_start_views]                    NVARCHAR (MAX)  NULL,
    [survey_start_clicks]                   NVARCHAR (MAX)  NULL,
    [survey_start_cvr]                      NVARCHAR (MAX)  NULL,
    [survey_finish]                         NVARCHAR (MAX)  NULL,
    [survey_finish_views]                   NVARCHAR (MAX)  NULL,
    [survey_finish_clicks]                  NVARCHAR (MAX)  NULL,
    [survey_finish_cvr]                     NVARCHAR (MAX)  NULL,
    [banner_interaction]                    NVARCHAR (MAX)  NULL,
    [banner_interaction_views]              NVARCHAR (MAX)  NULL,
    [banner_interaction_clicks]             NVARCHAR (MAX)  NULL,
    [banner_interaction_cvr]                NVARCHAR (MAX)  NULL,
    [widget_interaction]                    NVARCHAR (MAX)  NULL,
    [widget_interaction_views]              NVARCHAR (MAX)  NULL,
    [widget_interaction_clicks]             NVARCHAR (MAX)  NULL,
    [widget_interaction_cvr]                NVARCHAR (MAX)  NULL,
    [game_interaction]                      NVARCHAR (MAX)  NULL,
    [game_interaction_views]                NVARCHAR (MAX)  NULL,
    [game_interaction_clicks]               NVARCHAR (MAX)  NULL,
    [game_interaction_cvr]                  NVARCHAR (MAX)  NULL,
    [email_load]                            NVARCHAR (MAX)  NULL,
    [email_load_views]                      NVARCHAR (MAX)  NULL,
    [email_load_clicks]                     NVARCHAR (MAX)  NULL,
    [email_load_cvr]                        NVARCHAR (MAX)  NULL,
    [email_interaction]                     NVARCHAR (MAX)  NULL,
    [email_interaction_views]               NVARCHAR (MAX)  NULL,
    [email_interaction_clicks]              NVARCHAR (MAX)  NULL,
    [email_interaction_cvr]                 NVARCHAR (MAX)  NULL,
    [submit_button]                         NVARCHAR (MAX)  NULL,
    [submit_button_views]                   NVARCHAR (MAX)  NULL,
    [submit_button_clicks]                  NVARCHAR (MAX)  NULL,
    [submit_button_cvr]                     NVARCHAR (MAX)  NULL,
    [purchase_button]                       NVARCHAR (MAX)  NULL,
    [purchase_button_views]                 NVARCHAR (MAX)  NULL,
    [purchase_button_clicks]                NVARCHAR (MAX)  NULL,
    [purchase_button_cvr]                   NVARCHAR (MAX)  NULL,
    [click_on_redirect]                     NVARCHAR (MAX)  NULL,
    [click_on_redirect_views]               NVARCHAR (MAX)  NULL,
    [click_on_redirect_clicks]              NVARCHAR (MAX)  NULL,
    [click_on_redirect_cvr]                 NVARCHAR (MAX)  NULL,
    [drop_down_selection]                   NVARCHAR (MAX)  NULL,
    [drop_down_selection_views]             NVARCHAR (MAX)  NULL,
    [drop_down_selection_clicks]            NVARCHAR (MAX)  NULL,
    [drop_down_selection_cvr]               NVARCHAR (MAX)  NULL,
    [sign_up_button]                        NVARCHAR (MAX)  NULL,
    [sign_up_button_views]                  NVARCHAR (MAX)  NULL,
    [sign_up_button_clicks]                 NVARCHAR (MAX)  NULL,
    [sign_up_button_cvr]                    NVARCHAR (MAX)  NULL,
    [subscription_button]                   NVARCHAR (MAX)  NULL,
    [subscription_button_views]             NVARCHAR (MAX)  NULL,
    [subscription_button_clicks]            NVARCHAR (MAX)  NULL,
    [subscription_button_cvr]               NVARCHAR (MAX)  NULL,
    [success_page]                          NVARCHAR (MAX)  NULL,
    [success_page_views]                    NVARCHAR (MAX)  NULL,
    [success_page_clicks]                   NVARCHAR (MAX)  NULL,
    [success_page_cvr]                      NVARCHAR (MAX)  NULL,
    [thank_you_page]                        NVARCHAR (MAX)  NULL,
    [thank_you_page_views]                  NVARCHAR (MAX)  NULL,
    [thank_you_page_clicks]                 NVARCHAR (MAX)  NULL,
    [thank_you_page_cvr]                    NVARCHAR (MAX)  NULL,
    [registration_form]                     NVARCHAR (MAX)  NULL,
    [registration_form_views]               NVARCHAR (MAX)  NULL,
    [registration_form_clicks]              NVARCHAR (MAX)  NULL,
    [registration_form_cvr]                 NVARCHAR (MAX)  NULL,
    [registration_confirm_page]             NVARCHAR (MAX)  NULL,
    [registration_confirm_page_views]       NVARCHAR (MAX)  NULL,
    [registration_confirm_page_clicks]      NVARCHAR (MAX)  NULL,
    [registration_confirm_page_cvr]         NVARCHAR (MAX)  NULL,
    [store_locator_page]                    NVARCHAR (MAX)  NULL,
    [store_locator_page_views]              NVARCHAR (MAX)  NULL,
    [store_locator_page_clicks]             NVARCHAR (MAX)  NULL,
    [store_locator_page_cvr]                NVARCHAR (MAX)  NULL,
    [mobile_app_first_starts]               NVARCHAR (MAX)  NULL,
    [mobile_app_first_start_views]          NVARCHAR (MAX)  NULL,
    [mobile_app_first_start_clicks]         NVARCHAR (MAX)  NULL,
    [mobile_app_first_start_cvr]            NVARCHAR (MAX)  NULL,
    [brand_store_engagement_1]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_1_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_1_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_1_cvr]          NVARCHAR (MAX)  NULL,
    [brand_store_engagement_2]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_2_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_2_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_2_cvr]          NVARCHAR (MAX)  NULL,
    [brand_store_engagement_3]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_3_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_3_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_3_cvr]          NVARCHAR (MAX)  NULL,
    [brand_store_engagement_4]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_4_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_4_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_4_cvr]          NVARCHAR (MAX)  NULL,
    [brand_store_engagement_5]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_5_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_5_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_5_cvr]          NVARCHAR (MAX)  NULL,
    [brand_store_engagement_6]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_6_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_6_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_6_cvr]          NVARCHAR (MAX)  NULL,
    [brand_store_engagement_7]              NVARCHAR (MAX)  NULL,
    [brand_store_engagement_7_views]        NVARCHAR (MAX)  NULL,
    [brand_store_engagement_7_clicks]       NVARCHAR (MAX)  NULL,
    [brand_store_engagement_7_cvr]          NVARCHAR (MAX)  NULL,
    [atsc]                                  NVARCHAR (MAX)  NULL,
    [atsc_views]                            NVARCHAR (MAX)  NULL,
    [atsc_clicks]                           NVARCHAR (MAX)  NULL,
    [atsc_cvr]                              NVARCHAR (MAX)  NULL,
    [product_purchased]                     NVARCHAR (MAX)  NULL,
    [product_purchased_views]               NVARCHAR (MAX)  NULL,
    [product_purchased_clicks]              NVARCHAR (MAX)  NULL,
    [product_purchased_cvr]                 NVARCHAR (MAX)  NULL,
    [homepage_visit]                        NVARCHAR (MAX)  NULL,
    [homepage_visit_views]                  NVARCHAR (MAX)  NULL,
    [homepage_visit_clicks]                 NVARCHAR (MAX)  NULL,
    [homepage_visit_cvr]                    NVARCHAR (MAX)  NULL,
    [video_started]                         NVARCHAR (MAX)  NULL,
    [video_started_views]                   NVARCHAR (MAX)  NULL,
    [video_started_clicks]                  NVARCHAR (MAX)  NULL,
    [video_started_cvr]                     NVARCHAR (MAX)  NULL,
    [video_completed]                       NVARCHAR (MAX)  NULL,
    [video_completed_views]                 NVARCHAR (MAX)  NULL,
    [video_end_clicks]                      NVARCHAR (MAX)  NULL,
    [video_completed_cvr]                   NVARCHAR (MAX)  NULL,
    [message_sent]                          NVARCHAR (MAX)  NULL,
    [message_sent_views]                    NVARCHAR (MAX)  NULL,
    [message_sent_clicks]                   NVARCHAR (MAX)  NULL,
    [message_sent_cvr]                      NVARCHAR (MAX)  NULL,
    [mashup_click_to_page]                  NVARCHAR (MAX)  NULL,
    [mashup_click_to_page_views]            NVARCHAR (MAX)  NULL,
    [mashup_click_to_page_clicks]           NVARCHAR (MAX)  NULL,
    [mashup_click_to_page_cvr]              NVARCHAR (MAX)  NULL,
    [mashup_backup_image]                   NVARCHAR (MAX)  NULL,
    [mashup_backup_image_views]             NVARCHAR (MAX)  NULL,
    [mashup_backup_image_clicks]            NVARCHAR (MAX)  NULL,
    [mashup_backup_image_cvr]               NVARCHAR (MAX)  NULL,
    [mashup_atc]                            NVARCHAR (MAX)  NULL,
    [mashup_atc_views]                      NVARCHAR (MAX)  NULL,
    [mashup_atc_clicks]                     NVARCHAR (MAX)  NULL,
    [mashup_add_to_cart_click_cvr]          NVARCHAR (MAX)  NULL,
    [mashup_atw]                            NVARCHAR (MAX)  NULL,
    [mashup_atw_views]                      NVARCHAR (MAX)  NULL,
    [mashup_atw_clicks]                     NVARCHAR (MAX)  NULL,
    [mashup_atw_cvr]                        NVARCHAR (MAX)  NULL,
    [mashup_sns_click]                      NVARCHAR (MAX)  NULL,
    [mashup_sns_click_views]                NVARCHAR (MAX)  NULL,
    [mashup_sns_click_cvr]                  NVARCHAR (MAX)  NULL,
    [mashup_cc_click]                       NVARCHAR (MAX)  NULL,
    [mashup_cc_click_views]                 NVARCHAR (MAX)  NULL,
    [mashup_cc_click_clicks]                NVARCHAR (MAX)  NULL,
    [mashup_cc_click_cvr]                   NVARCHAR (MAX)  NULL,
    [mashup_sn_click]                       NVARCHAR (MAX)  NULL,
    [mashup_sn_click_views]                 NVARCHAR (MAX)  NULL,
    [mashup_sn_click_clicks]                NVARCHAR (MAX)  NULL,
    [mashup_sn_click_cvr]                   NVARCHAR (MAX)  NULL,
    [referral]                              NVARCHAR (MAX)  NULL,
    [referral_views]                        NVARCHAR (MAX)  NULL,
    [referral_clicks]                       NVARCHAR (MAX)  NULL,
    [referral_cvr]                          NVARCHAR (MAX)  NULL,
    [accept]                                NVARCHAR (MAX)  NULL,
    [accept_views]                          NVARCHAR (MAX)  NULL,
    [accept_clicks]                         NVARCHAR (MAX)  NULL,
    [accept_cvr]                            NVARCHAR (MAX)  NULL,
    [decline]                               NVARCHAR (MAX)  NULL,
    [decline_views]                         NVARCHAR (MAX)  NULL,
    [decline_clicks]                        NVARCHAR (MAX)  NULL,
    [decline_cvr]                           NVARCHAR (MAX)  NULL,
    [dpv]                                   NUMERIC (20, 4) NULL,
    [dpv_views]                             NUMERIC (20, 4) NULL,
    [dpv_clicks]                            NUMERIC (20, 4) NULL,
    [dpvr]                                  NUMERIC (20, 4) NULL,
    [prpv]                                  NUMERIC (20, 4) NULL,
    [prpv_views]                            NUMERIC (20, 4) NULL,
    [prpv_clicks]                           NUMERIC (20, 4) NULL,
    [prpvr]                                 NUMERIC (20, 4) NULL,
    [atl]                                   NVARCHAR (MAX)  NULL,
    [atl_views]                             NVARCHAR (MAX)  NULL,
    [atl_clicks]                            NVARCHAR (MAX)  NULL,
    [atlr]                                  NVARCHAR (MAX)  NULL,
    [atc]                                   NUMERIC (20, 4) NULL,
    [atc_views]                             NUMERIC (20, 4) NULL,
    [atc_clicks]                            NUMERIC (20, 4) NULL,
    [atcr]                                  NUMERIC (20, 4) NULL,
    [purchases]                             NUMERIC (20, 4) NULL,
    [purchases_views]                       NUMERIC (20, 4) NULL,
    [purchases_clicks]                      NUMERIC (20, 4) NULL,
    [purchase_rate]                         NUMERIC (20, 4) NULL,
    [newtobrand_purchases]                  NUMERIC (20, 4) NULL,
    [newtobrand_purchases_views]            NUMERIC (20, 4) NULL,
    [newtobrand_purchases_clicks]           NUMERIC (20, 4) NULL,
    [newtobrand_purchase_rate]              NUMERIC (20, 4) NULL,
    [percent_of_purchases_newtobrand]       NUMERIC (20, 4) NULL,
    [snss]                                  NVARCHAR (MAX)  NULL,
    [snss_views]                            NVARCHAR (MAX)  NULL,
    [snss_clicks]                           NVARCHAR (MAX)  NULL,
    [snssr]                                 NVARCHAR (MAX)  NULL,
    [atw]                                   NVARCHAR (MAX)  NULL,
    [atw_views]                             NVARCHAR (MAX)  NULL,
    [atw_clicks]                            NVARCHAR (MAX)  NULL,
    [atwr]                                  NVARCHAR (MAX)  NULL,
    [downloaded_video_plays]                NVARCHAR (MAX)  NULL,
    [downloaded_video_plays_views]          NVARCHAR (MAX)  NULL,
    [downloaded_video_plays_clicks]         NVARCHAR (MAX)  NULL,
    [downloaded_video_play_rate]            NVARCHAR (MAX)  NULL,
    [video_streams]                         NVARCHAR (MAX)  NULL,
    [video_streams_views]                   NVARCHAR (MAX)  NULL,
    [video_streams_clicks]                  NVARCHAR (MAX)  NULL,
    [video_streams_rate]                    NVARCHAR (MAX)  NULL,
    [play_trailers]                         NVARCHAR (MAX)  NULL,
    [play_trailers_views]                   NVARCHAR (MAX)  NULL,
    [player_trailers_clicks]                NVARCHAR (MAX)  NULL,
    [play_trailer_rate]                     NVARCHAR (MAX)  NULL,
    [rentals]                               NVARCHAR (MAX)  NULL,
    [rentals_views]                         NVARCHAR (MAX)  NULL,
    [rentals_clicks]                        NVARCHAR (MAX)  NULL,
    [rental_rate]                           NVARCHAR (MAX)  NULL,
    [video_downloads]                       NVARCHAR (MAX)  NULL,
    [video_downloads_views]                 NVARCHAR (MAX)  NULL,
    [video_downloads_clicks]                NVARCHAR (MAX)  NULL,
    [video_download_rate]                   NVARCHAR (MAX)  NULL,
    [video_start]                           NVARCHAR (MAX)  NULL,
    [video_first_quartile]                  NVARCHAR (MAX)  NULL,
    [video_midpoint]                        NVARCHAR (MAX)  NULL,
    [video_third_quartile]                  NVARCHAR (MAX)  NULL,
    [video_complete]                        NVARCHAR (MAX)  NULL,
    [video_completion_rate]                 NVARCHAR (MAX)  NULL,
    [video_pause]                           NVARCHAR (MAX)  NULL,
    [video_resume]                          NVARCHAR (MAX)  NULL,
    [video_mute]                            NVARCHAR (MAX)  NULL,
    [video_unmute]                          NVARCHAR (MAX)  NULL,
    [units_sold]                            NUMERIC (20, 4) NULL,
    [sales_cad]                             NUMERIC (20, 4) NULL,
    [newtobrand_units_sold]                 NUMERIC (20, 4) NULL,
    [newtobrand_product_sales_cad]          NUMERIC (20, 4) NULL,
    [total_dpv]                             NUMERIC (20, 4) NULL,
    [total_dpv_views]                       NUMERIC (20, 4) NULL,
    [total_dpv_clicks]                      NUMERIC (20, 4) NULL,
    [total_dpvr]                            NUMERIC (20, 4) NULL,
    [total_prpv]                            NUMERIC (20, 4) NULL,
    [total_prpv_views]                      NUMERIC (20, 4) NULL,
    [total_prpv_clicks]                     NUMERIC (20, 4) NULL,
    [total_prpvr]                           NUMERIC (20, 4) NULL,
    [total_atl]                             NVARCHAR (MAX)  NULL,
    [total_atl_views]                       NVARCHAR (MAX)  NULL,
    [total_atl_clicks]                      NVARCHAR (MAX)  NULL,
    [total_atlr]                            NVARCHAR (MAX)  NULL,
    [total_atc]                             NUMERIC (20, 4) NULL,
    [total_atc_views]                       NUMERIC (20, 4) NULL,
    [total_atc_clicks]                      NUMERIC (20, 4) NULL,
    [total_atcr]                            NUMERIC (20, 4) NULL,
    [total_purchases]                       NUMERIC (20, 4) NULL,
    [total_purchases_views]                 NUMERIC (20, 4) NULL,
    [total_purchases_clicks]                NUMERIC (20, 4) NULL,
    [total_purchase_rate]                   NUMERIC (20, 4) NULL,
    [total_newtobrand_purchases]            NUMERIC (20, 4) NULL,
    [total_newtobrand_purchases_views]      NUMERIC (20, 4) NULL,
    [total_newtobrand_purchases_clicks]     NUMERIC (20, 4) NULL,
    [total_newtobrand_purchase_rate]        NUMERIC (20, 4) NULL,
    [total_percent_of_purchases_newtobrand] NUMERIC (20, 4) NULL,
    [total_snss]                            NUMERIC (20, 4) NULL,
    [total_snss_views]                      NUMERIC (20, 4) NULL,
    [total_snss_clicks]                     NVARCHAR (MAX)  NULL,
    [total_snss_rate]                       NUMERIC (20, 4) NULL,
    [total_units_sold]                      NUMERIC (20, 4) NULL,
    [total_sales_cad]                       NUMERIC (20, 4) NULL,
    [total_newtobrand_units_sold]           NUMERIC (20, 4) NULL,
    [total_newtobrand_product_sales_cad]    NUMERIC (20, 4) NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CD_AMN_Display_All_Metrics_dt_filename]
    ON [dbo].[CD_AMN_Display_All_Metrics]([dt_filename] ASC);

