CREATE TABLE [dbo].[CD_Ams_Kenshoo] (
    [Currency]                      NVARCHAR (50)  NOT NULL,
    [Date]                          DATE           NOT NULL,
    [Ad_Group_Name]                 NVARCHAR (150) NOT NULL,
    [Campaign_Name]                 NVARCHAR (150) NOT NULL,
    [Channel]                       NVARCHAR (50)  NOT NULL,
    [Keyword]                       NVARCHAR (500) NOT NULL,
    [Profile_Name]                  NVARCHAR (50)  NOT NULL,
    [units_14_day]                  FLOAT (53)     NOT NULL,
    [Channel_Campaign_ID]           BIGINT         NOT NULL,
    [Channel_Keyword_ID]            BIGINT         NOT NULL,
    [Channel_Ad_Group_ID]           BIGINT         NOT NULL,
    [Channel_Account_ID]            BIGINT         NOT NULL,
    [Account_Name]                  NVARCHAR (250) NOT NULL,
    [Ad_Group_ID]                   BIGINT         NOT NULL,
    [AdGroup_ID_in_Kenshoo]         INT            NOT NULL,
    [AdGroup_Status]                NVARCHAR (50)  NOT NULL,
    [Bid]                           FLOAT (53)     NOT NULL,
    [Campaign_ID]                   INT            NOT NULL,
    [Campaign_Status]               NVARCHAR (50)  NOT NULL,
    [Channel_Account_Publisher_ID]  BIGINT         NOT NULL,
    [Custom_Parameter_1]            NVARCHAR (1)   NULL,
    [Custom_Parameter_2]            NVARCHAR (1)   NULL,
    [Custom_Parameter_3]            NVARCHAR (1)   NULL,
    [Keyword_Creation_Date]         DATETIME2 (7)  NOT NULL,
    [Keyword_ID]                    INT            NOT NULL,
    [Land_URL]                      NVARCHAR (1)   NULL,
    [Last_Modified]                 DATETIME2 (7)  NOT NULL,
    [Match_Type]                    NVARCHAR (50)  NOT NULL,
    [Min_Bid]                       FLOAT (53)     NULL,
    [Mobile_Bid_Adjustment]         NVARCHAR (1)   NULL,
    [Mobile_effective_bid]          NVARCHAR (1)   NULL,
    [Mobile_URL]                    NVARCHAR (1)   NULL,
    [Network]                       NVARCHAR (50)  NOT NULL,
    [Profile_Currency]              NVARCHAR (50)  NOT NULL,
    [Profile_ID]                    INT            NOT NULL,
    [Quality_Score]                 NVARCHAR (1)   NULL,
    [Status]                        NVARCHAR (50)  NOT NULL,
    [Tracking_ID]                   SMALLINT       NOT NULL,
    [Tracking_Template]             NVARCHAR (1)   NULL,
    [Upgr_URL_Ind]                  NVARCHAR (1)   NULL,
    [Avg_CPC]                       FLOAT (53)     NOT NULL,
    [Avg_Pos]                       FLOAT (53)     NOT NULL,
    [Clicks]                        FLOAT (53)     NOT NULL,
    [Conv_Rate]                     FLOAT (53)     NOT NULL,
    [Conversions]                   FLOAT (53)     NOT NULL,
    [Cost]                          FLOAT (53)     NOT NULL,
    [Cost_Conv]                     FLOAT (53)     NOT NULL,
    [CTR]                           FLOAT (53)     NOT NULL,
    [Imp_Share]                     FLOAT (53)     NOT NULL,
    [Impr_Abs_Top]                  FLOAT (53)     NOT NULL,
    [Impr_Top]                      FLOAT (53)     NOT NULL,
    [Impressions]                   FLOAT (53)     NOT NULL,
    [Lost_IS_rank]                  FLOAT (53)     NOT NULL,
    [Potential_Impressions]         FLOAT (53)     NOT NULL,
    [Profit]                        FLOAT (53)     NOT NULL,
    [Rev]                           FLOAT (53)     NOT NULL,
    [Rev_Conv]                      FLOAT (53)     NOT NULL,
    [ROI]                           FLOAT (53)     NOT NULL,
    [Search_Abs_Top_IS]             FLOAT (53)     NOT NULL,
    [Search_Top_IS]                 FLOAT (53)     NOT NULL,
    [_1_day]                        FLOAT (53)     NOT NULL,
    [_1_day_same_sku]               FLOAT (53)     NOT NULL,
    [_14_days]                      FLOAT (53)     NOT NULL,
    [_14_days_same_sku]             FLOAT (53)     NOT NULL,
    [_30_day]                       FLOAT (53)     NOT NULL,
    [_30_day_same_sku]              FLOAT (53)     NOT NULL,
    [_30_days]                      FLOAT (53)     NOT NULL,
    [_30_days_same_sku]             FLOAT (53)     NOT NULL,
    [_7_days]                       FLOAT (53)     NOT NULL,
    [_7_days_same_sku]              FLOAT (53)     NOT NULL,
    [conversions1]                  FLOAT (53)     NOT NULL,
    [new_to_brand_order_rate]       FLOAT (53)     NOT NULL,
    [new_to_brand_orders]           FLOAT (53)     NOT NULL,
    [new_to_brand_percentage]       FLOAT (53)     NOT NULL,
    [new_to_brand_units]            FLOAT (53)     NOT NULL,
    [new_to_brand_units_percentage] FLOAT (53)     NOT NULL,
    [page_views]                    FLOAT (53)     NOT NULL,
    [uc_conv]                       FLOAT (53)     NOT NULL,
    [units_1_day]                   FLOAT (53)     NOT NULL,
    [units_30_day]                  FLOAT (53)     NOT NULL,
    [units_7_day]                   FLOAT (53)     NOT NULL,
    [conv]                          FLOAT (53)     NOT NULL,
    [page_views1]                   FLOAT (53)     NOT NULL,
    [Brand_Non_Brand]               NVARCHAR (50)  NOT NULL,
    [Keyword_Targeting]             NVARCHAR (50)  NOT NULL,
    [Portfolio_Subsets]             NVARCHAR (50)  NOT NULL,
    [SOV_Keyword]                   NVARCHAR (50)  NOT NULL
);

