CREATE TABLE [dbo].[CD_FB_Ads_PP] (
    [dt_created]                               DATETIME        NULL,
    [dt_updated]                               DATETIME        NULL,
    [dt_filename]                              NVARCHAR (255)  NULL,
    [actionslink_click]                        BIGINT          NULL,
    [unique_actionscomment]                    BIGINT          NULL,
    [actionspost_reaction]                     BIGINT          NULL,
    [cpc]                                      NUMERIC (20, 4) NULL,
    [actionsvideo_view]                        BIGINT          NULL,
    [campaign_id]                              BIGINT          NULL,
    [actionspost_engagement]                   BIGINT          NULL,
    [cpp]                                      NUMERIC (20, 4) NULL,
    [actionsonsite_conversionpost_save]        BIGINT          NULL,
    [account_currency]                         NVARCHAR (MAX)  NULL,
    [adset_id]                                 BIGINT          NULL,
    [unique_actionspost_engagement]            BIGINT          NULL,
    [impressions]                              BIGINT          NULL,
    [ad_name]                                  NVARCHAR (MAX)  NULL,
    [objective]                                NVARCHAR (MAX)  NULL,
    [actionspage_engagement]                   BIGINT          NULL,
    [publisher_platform]                       NVARCHAR (MAX)  NULL,
    [video_p75_watched_actionsvideo_view]      BIGINT          NULL,
    [actionscomment]                           BIGINT          NULL,
    [actionspost]                              BIGINT          NULL,
    [campaign_name]                            NVARCHAR (MAX)  NULL,
    [account_id]                               BIGINT          NULL,
    [video_p100_watched_actionsvideo_view]     BIGINT          NULL,
    [cpm]                                      NUMERIC (20, 4) NULL,
    [unique_actionslink_click]                 BIGINT          NULL,
    [spend]                                    NUMERIC (20, 4) NULL,
    [date_stop]                                DATE            NULL,
    [date_start]                               DATE            NULL,
    [adset_name]                               NVARCHAR (MAX)  NULL,
    [buying_type]                              NVARCHAR (MAX)  NULL,
    [ad_id]                                    BIGINT          NULL,
    [unique_actionsonsite_conversionpost_save] BIGINT          NULL,
    [video_p95_watched_actionsvideo_view]      BIGINT          NULL,
    [reach]                                    BIGINT          NULL,
    [frequency]                                NUMERIC (20, 4) NULL,
    [website_ctrlink_click]                    NUMERIC (20, 4) NULL,
    [ctr]                                      NUMERIC (20, 4) NULL,
    [unique_actionspage_engagement]            BIGINT          NULL,
    [unique_actionsvideo_view]                 BIGINT          NULL,
    [video_play_actionsvideo_view]             BIGINT          NULL,
    [platform_position]                        NVARCHAR (MAX)  NULL,
    [video_p25_watched_actionsvideo_view]      BIGINT          NULL,
    [unique_actionspost_reaction]              BIGINT          NULL,
    [account_name]                             NVARCHAR (MAX)  NULL,
    [video_p50_watched_actionsvideo_view]      BIGINT          NULL,
    [clicks]                                   BIGINT          NULL,
    [unique_actionspost]                       BIGINT          NULL,
    [campaign_spend_cap]                       NVARCHAR (MAX)  NULL,
    [account_amount_spent]                     BIGINT          NULL,
    [campaign_stop_time]                       DATETIME        NULL,
    [account_account_status]                   BIGINT          NULL,
    [adset_budget_remaining]                   BIGINT          NULL,
    [account_balance]                          BIGINT          NULL,
    [ad_status]                                NVARCHAR (MAX)  NULL,
    [campaign_start_time]                      DATETIME        NULL,
    [account_business_city]                    NVARCHAR (MAX)  NULL,
    [adset_bid_amount]                         BIGINT          NULL,
    [account_spend_cap]                        BIGINT          NULL,
    [conversion_values]                        NVARCHAR (MAX)  NULL,
    [conversions]                              NUMERIC (20, 4) NULL,
    [outbound_clicks]                          NVARCHAR (MAX)  NULL,
    [social_spend]                             NVARCHAR (MAX)  NULL,
    [unique_actions]                           NVARCHAR (MAX)  NULL,
    [video_p100_watched_actions]               NVARCHAR (MAX)  NULL,
    [video_p25_watched_actions]                NVARCHAR (MAX)  NULL,
    [video_p50_watched_actions]                NVARCHAR (MAX)  NULL,
    [video_p75_watched_actions]                NVARCHAR (MAX)  NULL,
    [video_p95_watched_actions]                NVARCHAR (MAX)  NULL,
    [video_play_actions]                       NVARCHAR (MAX)  NULL,
    [website_ctr]                              NVARCHAR (MAX)  NULL,
    [website_purchase_roas]                    NVARCHAR (MAX)  NULL,
    [outbound_clicksoutbound_click]            BIGINT          NULL,
    [unique_actionsinteractive_component_tap]  BIGINT          NULL,
    [actionsinteractive_component_tap]         BIGINT          NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CD_FB_Ads_PP_dt_filename]
    ON [dbo].[CD_FB_Ads_PP]([dt_filename] ASC);

