CREATE TABLE [dbo].[CD_FB_Ads] (
    [dt_created]                                       DATETIME        NULL,
    [dt_updated]                                       DATETIME        NULL,
    [dt_filename]                                      NVARCHAR (255)  NULL,
    [actionslanding_page_view]                         BIGINT          NULL,
    [date_stop]                                        DATE            NULL,
    [actionspage_engagement]                           BIGINT          NULL,
    [account_id]                                       BIGINT          NULL,
    [actionsoffsite_conversionfb_pixel_add_to_cart]    BIGINT          NULL,
    [campaign_stop_time]                               DATETIME        NULL,
    [adset_id]                                         BIGINT          NULL,
    [campaign_id]                                      BIGINT          NULL,
    [date_start]                                       DATE            NULL,
    [spend]                                            NUMERIC (13, 4) NULL,
    [actionspost_engagement]                           BIGINT          NULL,
    [actionslink_click]                                BIGINT          NULL,
    [campaign_name]                                    NVARCHAR (MAX)  NULL,
    [objective]                                        NVARCHAR (MAX)  NULL,
    [impressions]                                      BIGINT          NULL,
    [actionspost_reaction]                             BIGINT          NULL,
    [actionsomni_add_to_cart]                          BIGINT          NULL,
    [account_name]                                     NVARCHAR (MAX)  NULL,
    [campaign_start_time]                              DATETIME        NULL,
    [adset_name]                                       NVARCHAR (MAX)  NULL,
    [actionspost]                                      BIGINT          NULL,
    [actionsonsite_conversionpost_save]                BIGINT          NULL,
    [actionscomment]                                   BIGINT          NULL,
    [actionsvideo_view]                                BIGINT          NULL,
    [video_p25_watched_actions]                        NVARCHAR (MAX)  NULL,
    [video_p75_watched_actionsvideo_view]              BIGINT          NULL,
    [clicks]                                           BIGINT          NULL,
    [video_p75_watched_actions]                        NVARCHAR (MAX)  NULL,
    [reach]                                            BIGINT          NULL,
    [video_p50_watched_actions]                        NVARCHAR (MAX)  NULL,
    [video_p100_watched_actions]                       NVARCHAR (MAX)  NULL,
    [video_p100_watched_actionsvideo_view]             BIGINT          NULL,
    [cpm]                                              NUMERIC (13, 4) NULL,
    [ctr]                                              NUMERIC (13, 4) NULL,
    [social_spend]                                     NVARCHAR (MAX)  NULL,
    [gender]                                           NVARCHAR (MAX)  NULL,
    [age]                                              NVARCHAR (MAX)  NULL,
    [cpc]                                              NUMERIC (13, 4) NULL,
    [video_p50_watched_actionsvideo_view]              BIGINT          NULL,
    [cpp]                                              NUMERIC (13, 4) NULL,
    [video_p25_watched_actionsvideo_view]              BIGINT          NULL,
    [campaign_spend_cap]                               NVARCHAR (MAX)  NULL,
    [actionsomni_purchase]                             BIGINT          NULL,
    [action_valuesomni_purchase]                       NUMERIC (13, 4) NULL,
    [action_valuesoffsite_conversionfb_pixel_purchase] NUMERIC (13, 4) NULL,
    [action_valuesomni_add_to_cart]                    BIGINT          NULL,
    [actionsoffsite_conversionfb_pixel_purchase]       BIGINT          NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CD_FB_Ads_dt_filename]
    ON [dbo].[CD_FB_Ads]([dt_filename] ASC);

