CREATE TABLE [dbo].[CD_Google_Ads_KW_AS] (
    [dt_created]                                 DATETIME        NULL,
    [dt_updated]                                 DATETIME        NULL,
    [dt_filename]                                NVARCHAR (255)  NULL,
    [client_customer_id]                         BIGINT          NULL,
    [client_customer_name]                       NVARCHAR (MAX)  NULL,
    [network_with_search_partners]               NVARCHAR (MAX)  NULL,
    [app_final_url]                              NVARCHAR (MAX)  NULL,
    [all_conv]                                   NUMERIC (13, 4) NULL,
    [engagement_rate]                            FLOAT (53)      NULL,
    [bidding_strategy_source]                    NVARCHAR (MAX)  NULL,
    [custom_parameter]                           VARCHAR (MAX)   NULL,
    [max_cpc]                                    NVARCHAR (MAX)  NULL,
    [enhanced_cpc_enabled]                       NVARCHAR (MAX)  NULL,
    [avg_position]                               NVARCHAR (MAX)  NULL,
    [active_view_viewable_impressions]           BIGINT          NULL,
    [clicks]                                     BIGINT          NULL,
    [max_cpm]                                    NVARCHAR (MAX)  NULL,
    [time_zone]                                  NVARCHAR (MAX)  NULL,
    [interactions]                               BIGINT          NULL,
    [search_lost_abs_top_is_budget]              NUMERIC (13, 4) NULL,
    [final_url_suffix]                           NVARCHAR (MAX)  NULL,
    [label_ids]                                  NVARCHAR (MAX)  NULL,
    [active_view_measurable_impr__impr]          FLOAT (53)      NULL,
    [cost__all_conv]                             NUMERIC (13, 4) NULL,
    [conversions]                                NUMERIC (13, 4) NULL,
    [account]                                    NVARCHAR (MAX)  NULL,
    [keyword]                                    NVARCHAR (MAX)  NULL,
    [video_played_to_75]                         FLOAT (53)      NULL,
    [match_type]                                 NVARCHAR (MAX)  NULL,
    [search_exact_match_is]                      NVARCHAR (MAX)  NULL,
    [quarter]                                    DATE            NULL,
    [active_view_viewable_impr__measurable_impr] FLOAT (53)      NULL,
    [est_add_costwk_first_position_bid]          NVARCHAR (MAX)  NULL,
    [campaign]                                   NVARCHAR (MAX)  NULL,
    [campaign_id]                                BIGINT          NULL,
    [labels]                                     NVARCHAR (MAX)  NULL,
    [landing_page_experience]                    NVARCHAR (MAX)  NULL,
    [interaction_rate]                           FLOAT (53)      NULL,
    [gmail_forwards]                             BIGINT          NULL,
    [active_view_avg_cpm]                        NUMERIC (13, 4) NULL,
    [avg_cpe]                                    NUMERIC (13, 4) NULL,
    [active_view_viewable_ctr]                   FLOAT (53)      NULL,
    [avg_cpc]                                    NUMERIC (13, 4) NULL,
    [avg_cpm]                                    NUMERIC (13, 4) NULL,
    [bid_strategy_type]                          NVARCHAR (MAX)  NULL,
    [gmail_saves]                                BIGINT          NULL,
    [avg_cpv]                                    NUMERIC (13, 4) NULL,
    [impr_abs_top_]                              NUMERIC (13, 4) NULL,
    [criterion_serving_status]                   NVARCHAR (MAX)  NULL,
    [video_played_to_100]                        FLOAT (53)      NULL,
    [vertical_id]                                BIGINT          NULL,
    [active_view_measurable_cost]                NUMERIC (13, 4) NULL,
    [all_conv_rate]                              FLOAT (53)      NULL,
    [search_lost_top_is_rank]                    NUMERIC (13, 4) NULL,
    [value__conv_current_model]                  NUMERIC (13, 4) NULL,
    [view_rate]                                  FLOAT (53)      NULL,
    [engagements]                                BIGINT          NULL,
    [active_view_measurable_impr]                BIGINT          NULL,
    [conv_rate]                                  FLOAT (53)      NULL,
    [quality_score]                              NVARCHAR (MAX)  NULL,
    [bid_strategy_name]                          NVARCHAR (MAX)  NULL,
    [all_conv_value]                             NUMERIC (13, 4) NULL,
    [approval_status]                            NVARCHAR (MAX)  NULL,
    [search_lost_is_rank]                        NVARCHAR (MAX)  NULL,
    [search_abs_top_is]                          NVARCHAR (MAX)  NULL,
    [views]                                      BIGINT          NULL,
    [customer_id]                                BIGINT          NULL,
    [conv_value_current_model]                   NUMERIC (13, 4) NULL,
    [ad_group_id]                                BIGINT          NULL,
    [month]                                      DATE            NULL,
    [currency]                                   NVARCHAR (MAX)  NULL,
    [total_conv_value]                           NUMERIC (13, 4) NULL,
    [final_url]                                  NVARCHAR (MAX)  NULL,
    [max_cpc_source]                             NVARCHAR (MAX)  NULL,
    [interaction_types]                          NVARCHAR (MAX)  NULL,
    [crossdevice_conv]                           NVARCHAR (MAX)  NULL,
    [video_played_to_25]                         FLOAT (53)      NULL,
    [viewthrough_conv]                           BIGINT          NULL,
    [ad_relevance]                               NVARCHAR (MAX)  NULL,
    [ad_group]                                   NVARCHAR (MAX)  NULL,
    [network]                                    NVARCHAR (MAX)  NULL,
    [week]                                       DATE            NULL,
    [client_name]                                NVARCHAR (MAX)  NULL,
    [cost__conv]                                 NUMERIC (13, 4) NULL,
    [expected_clickthrough_rate]                 NVARCHAR (MAX)  NULL,
    [day_of_week]                                NVARCHAR (MAX)  NULL,
    [value__conv]                                NUMERIC (13, 4) NULL,
    [device]                                     NVARCHAR (MAX)  NULL,
    [tracking_template]                          NVARCHAR (MAX)  NULL,
    [search_impr_share]                          NVARCHAR (MAX)  NULL,
    [search_lost_abs_top_is_rank]                NUMERIC (13, 4) NULL,
    [has_quality_score]                          NVARCHAR (MAX)  NULL,
    [first_page_cpc]                             BIGINT          NULL,
    [bid_strategy_id]                            BIGINT          NULL,
    [value__all_conv]                            NUMERIC (13, 4) NULL,
    [video_played_to_50]                         FLOAT (53)      NULL,
    [keyword_state]                              NVARCHAR (MAX)  NULL,
    [conversions_current_model]                  NUMERIC (13, 4) NULL,
    [est_add_clickswk_first_position_bid]        NVARCHAR (MAX)  NULL,
    [top_of_page_cpc]                            BIGINT          NULL,
    [keyword_id]                                 BIGINT          NULL,
    [day]                                        DATE            NULL,
    [avg_cost]                                   NUMERIC (13, 4) NULL,
    [impressions]                                BIGINT          NULL,
    [base_ad_group_id]                           BIGINT          NULL,
    [search_top_is]                              NUMERIC (13, 4) NULL,
    [first_position_cpc]                         NVARCHAR (MAX)  NULL,
    [campaign_state]                             NVARCHAR (MAX)  NULL,
    [destination_url]                            NVARCHAR (MAX)  NULL,
    [ad_group_state]                             NVARCHAR (MAX)  NULL,
    [mobile_final_url]                           NVARCHAR (MAX)  NULL,
    [cost__conv_current_model]                   NUMERIC (13, 4) NULL,
    [search_lost_top_is_budget]                  NUMERIC (13, 4) NULL,
    [is_negative]                                NVARCHAR (MAX)  NULL,
    [base_campaign_id]                           BIGINT          NULL,
    [gmail_clicks_to_website]                    BIGINT          NULL,
    [month_of_year]                              NVARCHAR (MAX)  NULL,
    [cost]                                       NUMERIC (13, 4) NULL,
    [year]                                       BIGINT          NULL,
    [impr_top_]                                  NUMERIC (13, 4) NULL,
    [video_plays_25]                             NUMERIC (13, 4) NULL,
    [video_plays_50]                             NUMERIC (13, 4) NULL,
    [video_plays_75]                             NUMERIC (13, 4) NULL,
    [video_plays_100]                            NUMERIC (13, 4) NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CD_Google_Ads_KW_AS_dt_filename]
    ON [dbo].[CD_Google_Ads_KW_AS]([dt_filename] ASC);

