CREATE TABLE [dbo].[CD_GCM_Ads] (
    [dt_created]                                         DATETIME        NULL,
    [dt_updated]                                         DATETIME        NULL,
    [dt_filename]                                        NVARCHAR (255)  NULL,
    [creative_id]                                        NVARCHAR (MAX)  NULL,
    [date]                                               DATE            NULL,
    [clickthrough_url]                                   NVARCHAR (MAX)  NULL,
    [ad_id]                                              BIGINT          NULL,
    [campaign_id]                                        BIGINT          NULL,
    [placement]                                          NVARCHAR (MAX)  NULL,
    [advertiser_group]                                   NVARCHAR (MAX)  NULL,
    [campaign_end_date]                                  DATE            NULL,
    [placement_end_date]                                 DATE            NULL,
    [placement_start_date]                               DATE            NULL,
    [advertiser]                                         NVARCHAR (MAX)  NULL,
    [creative]                                           NVARCHAR (MAX)  NULL,
    [placement_cost_structure]                           NVARCHAR (MAX)  NULL,
    [ad]                                                 NVARCHAR (MAX)  NULL,
    [placement_id]                                       BIGINT          NULL,
    [site_dcm]                                           NVARCHAR (MAX)  NULL,
    [advertiser_id]                                      BIGINT          NULL,
    [ad_status]                                          NVARCHAR (MAX)  NULL,
    [ad_type]                                            NVARCHAR (MAX)  NULL,
    [site_id_dcm]                                        BIGINT          NULL,
    [campaign]                                           NVARCHAR (MAX)  NULL,
    [creative_type]                                      NVARCHAR (MAX)  NULL,
    [campaign_start_date]                                DATE            NULL,
    [clicks]                                             BIGINT          NULL,
    [impressions]                                        BIGINT          NULL,
    [total_conversions]                                  NUMERIC (13, 4) NULL,
    [total_revenue]                                      NUMERIC (13, 4) NULL,
    [video_views]                                        BIGINT          NULL,
    [video_completions]                                  BIGINT          NULL,
    [viewthrough_conversions]                            NUMERIC (13, 4) NULL,
    [viewthrough_revenue]                                NUMERIC (13, 4) NULL,
    [click_rate]                                         NUMERIC (13, 4) NULL,
    [companion_clicks]                                   BIGINT          NULL,
    [video_companion_clicks]                             BIGINT          NULL,
    [companion_views]                                    BIGINT          NULL,
    [video_average_view_time]                            NUMERIC (13, 4) NULL,
    [video_first_quartile_completions]                   BIGINT          NULL,
    [video_fullscreen]                                   BIGINT          NULL,
    [video_interaction_rate]                             NUMERIC (13, 4) NULL,
    [fullscreen_video_plays]                             BIGINT          NULL,
    [video_interactions]                                 BIGINT          NULL,
    [video_mutes]                                        BIGINT          NULL,
    [video_midpoints]                                    BIGINT          NULL,
    [video_pauses]                                       BIGINT          NULL,
    [video_plays]                                        BIGINT          NULL,
    [video_skips]                                        BIGINT          NULL,
    [video_replays]                                      BIGINT          NULL,
    [video_progress_events]                              BIGINT          NULL,
    [video_unmutes]                                      BIGINT          NULL,
    [video_third_quartile_completions]                   BIGINT          NULL,
    [video_stops]                                        BIGINT          NULL,
    [video_view_rate]                                    NUMERIC (13, 4) NULL,
    [fullscreen_video_completions]                       BIGINT          NULL,
    [downloaded_impressions]                             BIGINT          NULL,
    [fullscreen_impressions]                             BIGINT          NULL,
    [fullscreen_average_view_time]                       NUMERIC (13, 4) NULL,
    [interaction_rate]                                   FLOAT (53)      NULL,
    [interactive_impressions]                            BIGINT          NULL,
    [average_interaction_time]                           NUMERIC (13, 4) NULL,
    [total_interaction_time]                             BIGINT          NULL,
    [total_interactions]                                 BIGINT          NULL,
    [roadblock_impressions]                              BIGINT          NULL,
    [total_display_time]                                 BIGINT          NULL,
    [trueview_views]                                     BIGINT          NULL,
    [active_view__measurable_impressions]                NUMERIC (13, 4) NULL,
    [active_view__viewable_impressions]                  NUMERIC (13, 4) NULL,
    [active_view__fullscreen]                            NUMERIC (13, 4) NULL,
    [active_view__visible_at_completion]                 NUMERIC (13, 4) NULL,
    [active_view__visible_at_first_quartile]             NUMERIC (13, 4) NULL,
    [active_view__visible_at_midpoint]                   NUMERIC (13, 4) NULL,
    [active_view__visible_at_start]                      NUMERIC (13, 4) NULL,
    [active_view__visible_at_third_quartile]             NUMERIC (13, 4) NULL,
    [active_view__of_completed_impressions_visible]      NUMERIC (13, 4) NULL,
    [active_view__play_time_visible]                     NUMERIC (13, 4) NULL,
    [active_view__of_first_quartile_impressions_visible] NUMERIC (13, 4) NULL,
    [active_view__of_midpoint_impressions_visible]       NUMERIC (13, 4) NULL,
    [active_view__of_third_quartile_impressions_visible] NUMERIC (13, 4) NULL,
    [active_view_eligible_impressions]                   BIGINT          NULL,
    [active_view_average_viewable_time_seconds]          NUMERIC (13, 4) NULL,
    [active_view_impression_distribution_viewable]       NUMERIC (13, 4) NULL,
    [active_view_measurable_impressions]                 BIGINT          NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CD_GCM_Ads1_dt_filename]
    ON [dbo].[CD_GCM_Ads]([dt_filename] ASC);


GO
CREATE TRIGGER [Trigger]
	ON [dbo].[CD_GCM_Ads]
	FOR DELETE, INSERT, UPDATE
	AS
	BEGIN
		SET NOCOUNT ON
	END