CREATE TABLE [dbo].[GCM_Demo] (
    [dt_created]                                                                                 DATETIME        NULL,
    [dt_updated]                                                                                 DATETIME        NULL,
    [dt_filename]                                                                                NVARCHAR (255)  NULL,
    [placement_id]                                                                               BIGINT          NULL,
    [site_dcm]                                                                                   NVARCHAR (MAX)  NULL,
    [advertiser_id]                                                                              BIGINT          NULL,
    [creative_id]                                                                                NVARCHAR (MAX)  NULL,
    [campaign_start_date]                                                                        DATE            NULL,
    [date]                                                                                       DATE            NULL,
    [campaign]                                                                                   NVARCHAR (MAX)  NULL,
    [creative_type]                                                                              NVARCHAR (MAX)  NULL,
    [advertiser]                                                                                 NVARCHAR (MAX)  NULL,
    [site_id_dcm]                                                                                BIGINT          NULL,
    [campaign_id]                                                                                BIGINT          NULL,
    [activity]                                                                                   NVARCHAR (MAX)  NULL,
    [creative]                                                                                   NVARCHAR (MAX)  NULL,
    [placement]                                                                                  NVARCHAR (MAX)  NULL,
    [campaign_end_date]                                                                          DATE            NULL,
    [clicks]                                                                                     BIGINT          NULL,
    [impressions]                                                                                BIGINT          NULL,
    [total_conversions]                                                                          NUMERIC (13, 4) NULL,
    [total_revenue]                                                                              NUMERIC (13, 4) NULL,
    [video_views]                                                                                BIGINT          NULL,
    [video_completions]                                                                          BIGINT          NULL,
    [media_cost]                                                                                 NUMERIC (13, 4) NULL,
    [fullscreen_video_completions]                                                               BIGINT          NULL,
    [active_view__visible_at_completion]                                                         NUMERIC (13, 4) NULL,
    [active_view__visible_at_first_quartile]                                                     NUMERIC (13, 4) NULL,
    [active_view__visible_at_midpoint]                                                           NUMERIC (13, 4) NULL,
    [active_view__visible_at_start]                                                              NUMERIC (13, 4) NULL,
    [active_view__visible_at_third_quartile]                                                     NUMERIC (13, 4) NULL,
    [companion_clicks]                                                                           BIGINT          NULL,
    [companion_impressions]                                                                      BIGINT          NULL,
    [video_plays]                                                                                BIGINT          NULL,
    [video_first_quartile_completions]                                                           BIGINT          NULL,
    [video_midpoints]                                                                            BIGINT          NULL,
    [video_third_quartile_completions]                                                           BIGINT          NULL,
    [video_progress_events]                                                                      BIGINT          NULL,
    [video_skips]                                                                                BIGINT          NULL,
    [video_mutes]                                                                                BIGINT          NULL,
    [video_pauses]                                                                               BIGINT          NULL,
    [video_fullscreen]                                                                           BIGINT          NULL,
    [active_view_impressions_visible_10_seconds]                                                 BIGINT          NULL,
    [downloaded_impressions]                                                                     BIGINT          NULL,
    [viewthrough_revenue]                                                                        NUMERIC (13, 4) NULL,
    [viewthrough_conversions]                                                                    NUMERIC (13, 4) NULL,
    [fullscreen_video_plays]                                                                     BIGINT          NULL,
    [video_companion_clicks]                                                                     BIGINT          NULL,
    [video_interactions]                                                                         BIGINT          NULL,
    [video_interaction_rate]                                                                     NUMERIC (13, 4) NULL,
    [video_replays]                                                                              BIGINT          NULL,
    [video_stops]                                                                                BIGINT          NULL,
    [video_unmutes]                                                                              BIGINT          NULL,
    [video_view_rate]                                                                            NUMERIC (13, 4) NULL,
    [video_average_view_time]                                                                    NUMERIC (13, 4) NULL,
    [active_view__audible_impressions]                                                           NUMERIC (13, 4) NULL,
    [active_view__audible_and_visible_at_completion]                                             NUMERIC (13, 4) NULL,
    [active_view_impression_distribution_viewable]                                               NUMERIC (13, 4) NULL,
    [active_view__audible_and_visible_at_first_quartile]                                         NUMERIC (13, 4) NULL,
    [active_view__audible_and_visible_at_midpoint]                                               NUMERIC (13, 4) NULL,
    [active_view__audible_and_visible_at_start]                                                  NUMERIC (13, 4) NULL,
    [active_view__audible_and_visible_at_third_quartile]                                         NUMERIC (13, 4) NULL,
    [active_view__fullscreen]                                                                    NUMERIC (13, 4) NULL,
    [active_view__in_background]                                                                 NUMERIC (13, 4) NULL,
    [active_view__measurable_impressions]                                                        NUMERIC (13, 4) NULL,
    [active_view__play_time_audible]                                                             NUMERIC (13, 4) NULL,
    [active_view__play_time_audible_and_visible]                                                 NUMERIC (13, 4) NULL,
    [active_view__play_time_visible]                                                             NUMERIC (13, 4) NULL,
    [active_view__viewable_impressions]                                                          NUMERIC (13, 4) NULL,
    [active_view__visible_10_seconds]                                                            NUMERIC (13, 4) NULL,
    [active_view__of_completed_impressions_audible_and_visible]                                  NUMERIC (13, 4) NULL,
    [active_view__of_completed_impressions_visible]                                              NUMERIC (13, 4) NULL,
    [active_view__of_first_quartile_impressions_audible_and_visible]                             NUMERIC (13, 4) NULL,
    [active_view__of_first_quartile_impressions_visible]                                         NUMERIC (13, 4) NULL,
    [active_view__of_midpoint_impressions_audible_and_visible]                                   NUMERIC (13, 4) NULL,
    [active_view__of_midpoint_impressions_visible]                                               NUMERIC (13, 4) NULL,
    [active_view__of_third_quartile_impressions_audible_and_visible]                             NUMERIC (13, 4) NULL,
    [active_view__of_third_quartile_impressions_visible]                                         NUMERIC (13, 4) NULL,
    [active_view_audible__fully_onscreen_for_half_of_duration_15_sec_cap_impressions]            BIGINT          NULL,
    [active_view_audible__fully_onscreen_for_half_of_duration_15_sec_cap_rate]                   NUMERIC (13, 4) NULL,
    [active_view_audible__fully_onscreen_for_half_of_duration_trueview_impressions]              BIGINT          NULL,
    [active_view_audible__fully_onscreen_for_half_of_duration_15_sec_cap_measurable_impressions] BIGINT          NULL,
    [active_view_audible__fully_onscreen_for_half_of_duration_trueview_measurable_impressions]   BIGINT          NULL,
    [active_view_audible__fully_onscreen_for_half_of_duration_trueview_rate]                     NUMERIC (13, 4) NULL,
    [active_view_eligible_impressions]                                                           BIGINT          NULL,
    [active_view_average_viewable_time_seconds]                                                  NUMERIC (13, 4) NULL,
    [active_view_impression_distribution_not_measurable]                                         NUMERIC (13, 4) NULL,
    [active_view_impression_distribution_not_viewable]                                           NUMERIC (13, 4) NULL,
    [active_view_impressions_audible_and_visible_at_completion]                                  BIGINT          NULL,
    [active_view_not_measurable_impressions]                                                     BIGINT          NULL,
    [active_view_measurable_impressions]                                                         BIGINT          NULL,
    [active_view_viewable_impressions]                                                           BIGINT          NULL,
    [active_view_not_viewable_impressions]                                                       BIGINT          NULL,
    [activity_per_click]                                                                         NUMERIC (13, 4) NULL,
    [average_time]                                                                               NUMERIC (13, 4) NULL,
    [average_display_time]                                                                       NUMERIC (13, 4) NULL,
    [activity_delivery_status]                                                                   NUMERIC (13, 4) NULL,
    [backup_image]                                                                               BIGINT          NULL,
    [booked_clicks]                                                                              NUMERIC (13, 4) NULL,
    [booked_impressions]                                                                         NUMERIC (13, 4) NULL,
    [activity_per_thousand_impressions]                                                          NUMERIC (13, 4) NULL,
    [booked_activities]                                                                          NUMERIC (13, 4) NULL,
    [booked_viewable_impressions]                                                                NUMERIC (13, 4) NULL,
    [click_delivery_status]                                                                      NUMERIC (13, 4) NULL,
    [click_rate]                                                                                 NUMERIC (13, 4) NULL,
    [clickthrough_conversions]                                                                   NUMERIC (13, 4) NULL,
    [cost_per_activity]                                                                          NUMERIC (13, 4) NULL,
    [clickthrough_revenue]                                                                       NUMERIC (13, 4) NULL,
    [code_serves]                                                                                BIGINT          NULL,
    [cost_per_revenue]                                                                           NUMERIC (13, 4) NULL,
    [cost_per_click]                                                                             NUMERIC (13, 4) NULL,
    [dbm_cost_account_currency]                                                                  NUMERIC (13, 4) NULL,
    [dbm_cost_usd]                                                                               NUMERIC (13, 4) NULL,
    [effective_cpm]                                                                              NUMERIC (13, 4) NULL,
    [event_timers]                                                                               NUMERIC (13, 4) NULL,
    [expansions]                                                                                 BIGINT          NULL,
    [planned_media_cost]                                                                         NUMERIC (13, 4) NULL
);

