CREATE TABLE [dbo].[Nestle_Social_Twitter_Ads] (
    [dt_created]                                                            DATETIME        NULL,
    [dt_updated]                                                            DATETIME        NULL,
    [dt_filename]                                                           NVARCHAR (150)  NULL,
    [mobile_conversion_loginspost_view]                                     NVARCHAR (50)   NULL,
    [conversion_sign_upssale_amount_view]                                   NVARCHAR (50)   NULL,
    [campaign_end_date]                                                     NVARCHAR (50)   NULL,
    [replies]                                                               NVARCHAR (50)   NULL,
    [campaign]                                                              NVARCHAR (MAX)  NULL,
    [mobile_conversion_loginssale_amount]                                   NVARCHAR (50)   NULL,
    [conversion_purchasesassisted]                                          NVARCHAR (50)   NULL,
    [conversion_customsale_amount_view]                                     NVARCHAR (50)   NULL,
    [retweets]                                                              NVARCHAR (50)   NULL,
    [conversion_purchasessale_amount_engagement]                            NVARCHAR (50)   NULL,
    [mobile_conversion_loginsorder_quantity]                                NVARCHAR (50)   NULL,
    [account_id]                                                            NVARCHAR (50)   NULL,
    [timestamp]                                                             DATE            NULL,
    [mobile_conversion_loginsassisted]                                      NVARCHAR (50)   NULL,
    [media_views]                                                           BIGINT          NULL,
    [conversion_customorder_quantity_view]                                  NVARCHAR (50)   NULL,
    [conversion_downloadspost_view]                                         NVARCHAR (50)   NULL,
    [campaign_id_ui]                                                        NVARCHAR (50)   NULL,
    [follows]                                                               NVARCHAR (50)   NULL,
    [conversion_site_visitspost_view]                                       NVARCHAR (50)   NULL,
    [mobile_conversion_reservationssale_amount]                             NVARCHAR (50)   NULL,
    [video_views_25]                                                        BIGINT          NULL,
    [mobile_conversion_sign_upssale_amount]                                 NVARCHAR (50)   NULL,
    [conversion_customorder_quantity]                                       NVARCHAR (50)   NULL,
    [conversion_purchasessale_amount]                                       NVARCHAR (50)   NULL,
    [campaign_id]                                                           BIGINT          NULL,
    [line_item_id_ui]                                                       NVARCHAR (50)   NULL,
    [app_clicks]                                                            NVARCHAR (50)   NULL,
    [video_views_100]                                                       BIGINT          NULL,
    [impressions]                                                           BIGINT          NULL,
    [card_engagements]                                                      NVARCHAR (50)   NULL,
    [media_engagements]                                                     BIGINT          NULL,
    [mobile_conversion_purchasespost_view]                                  NVARCHAR (50)   NULL,
    [conversion_custommetric]                                               NVARCHAR (50)   NULL,
    [mobile_conversion_site_visitspost_view]                                NVARCHAR (50)   NULL,
    [conversion_site_visitssale_amount_engagement]                          NVARCHAR (50)   NULL,
    [media_landing_url]                                                     NVARCHAR (50)   NULL,
    [conversion_sign_upsassisted]                                           NVARCHAR (50)   NULL,
    [conversion_purchasessale_amount_view]                                  NVARCHAR (50)   NULL,
    [video_views_75]                                                        BIGINT          NULL,
    [conversion_downloadspost_engagement]                                   NVARCHAR (50)   NULL,
    [conversion_custompost_engagement]                                      NVARCHAR (50)   NULL,
    [conversion_purchasespost_engagement]                                   NVARCHAR (50)   NULL,
    [mobile_conversion_sign_upsorder_quantity]                              NVARCHAR (50)   NULL,
    [mobile_conversion_purchasessale_amount]                                NVARCHAR (50)   NULL,
    [tweets_send]                                                           NVARCHAR (50)   NULL,
    [conversion_downloadssale_amount_engagement]                            NVARCHAR (50)   NULL,
    [conversion_sign_upsorder_quantity_engagement]                          NVARCHAR (50)   NULL,
    [mobile_conversion_reservationspost_view]                               NVARCHAR (50)   NULL,
    [conversion_custompost_view]                                            NVARCHAR (50)   NULL,
    [mobile_conversion_downloadspost_view]                                  NVARCHAR (50)   NULL,
    [mobile_conversion_site_visitssale_amount]                              NVARCHAR (50)   NULL,
    [conversion_downloadsorder_quantity]                                    NVARCHAR (50)   NULL,
    [unfollows]                                                             NVARCHAR (50)   NULL,
    [conversion_sign_upspost_view]                                          NVARCHAR (50)   NULL,
    [conversion_sign_upssale_amount]                                        NVARCHAR (50)   NULL,
    [mobile_conversion_downloadspost_engagement]                            NVARCHAR (50)   NULL,
    [likes]                                                                 BIGINT          NULL,
    [campaign_name]                                                         NVARCHAR (MAX)  NULL,
    [mobile_conversion_purchasespost_engagement]                            NVARCHAR (50)   NULL,
    [conversion_downloadssale_amount]                                       NVARCHAR (50)   NULL,
    [conversion_purchasesmetric]                                            NVARCHAR (50)   NULL,
    [conversion_downloadsorder_quantity_engagement]                         NVARCHAR (50)   NULL,
    [campaign_currency]                                                     NVARCHAR (50)   NULL,
    [conversion_site_visitsorder_quantity_view]                             NVARCHAR (50)   NULL,
    [conversion_sign_upssale_amount_engagement]                             NVARCHAR (50)   NULL,
    [conversion_customsale_amount_engagement]                               NVARCHAR (50)   NULL,
    [conversion_site_visitspost_engagement]                                 NVARCHAR (50)   NULL,
    [conversion_downloadsorder_quantity_view]                               NVARCHAR (50)   NULL,
    [mobile_conversion_site_visitsorder_quantity]                           NVARCHAR (50)   NULL,
    [media_id]                                                              NVARCHAR (50)   NULL,
    [conversion_downloadssale_amount_view]                                  NVARCHAR (50)   NULL,
    [mobile_conversion_loginspost_engagement]                               NVARCHAR (50)   NULL,
    [conversion_sign_upsorder_quantity_view]                                NVARCHAR (50)   NULL,
    [mobile_conversion_sign_upspost_engagement]                             NVARCHAR (50)   NULL,
    [account]                                                               NVARCHAR (250)  NULL,
    [mobile_conversion_sign_upsassisted]                                    NVARCHAR (50)   NULL,
    [type]                                                                  NVARCHAR (50)   NULL,
    [conversion_site_visitsorder_quantity_engagement]                       NVARCHAR (50)   NULL,
    [conversion_site_visitssale_amount]                                     NVARCHAR (50)   NULL,
    [mobile_conversion_purchasesorder_quantity]                             NVARCHAR (50)   NULL,
    [video_views_50]                                                        BIGINT          NULL,
    [mobile_conversion_purchasesassisted]                                   NVARCHAR (50)   NULL,
    [mobile_conversion_sign_upspost_view]                                   NVARCHAR (50)   NULL,
    [conversion_customsale_amount]                                          NVARCHAR (50)   NULL,
    [line_item_id]                                                          NVARCHAR (250)  NULL,
    [conversion_purchasesorder_quantity_engagement]                         NVARCHAR (50)   NULL,
    [mobile_conversion_reservationsassisted]                                NVARCHAR (50)   NULL,
    [conversion_site_visitssale_amount_view]                                NVARCHAR (50)   NULL,
    [conversion_site_visitsorder_quantity]                                  NVARCHAR (50)   NULL,
    [url_clicks]                                                            BIGINT          NULL,
    [objective]                                                             NVARCHAR (50)   NULL,
    [video_total_views]                                                     BIGINT          NULL,
    [clicks]                                                                BIGINT          NULL,
    [mobile_conversion_downloadssale_amount]                                NVARCHAR (50)   NULL,
    [conversion_purchasespost_view]                                         NVARCHAR (50)   NULL,
    [campaign_start_date]                                                   NVARCHAR (50)   NULL,
    [mobile_conversion_site_visitspost_engagement]                          NVARCHAR (50)   NULL,
    [mobile_conversion_reservationsorder_quantity]                          NVARCHAR (50)   NULL,
    [billed_engagements]                                                    NVARCHAR (50)   NULL,
    [engagements]                                                           BIGINT          NULL,
    [mobile_conversion_reservationspost_engagement]                         NVARCHAR (50)   NULL,
    [conversion_purchasesorder_quantity_view]                               NVARCHAR (50)   NULL,
    [conversion_site_visitsmetric]                                          NVARCHAR (50)   NULL,
    [conversion_sign_upspost_engagement]                                    NVARCHAR (50)   NULL,
    [conversion_customorder_quantity_engagement]                            NVARCHAR (50)   NULL,
    [line_item_name]                                                        NVARCHAR (MAX)  NULL,
    [conversion_sign_upsmetric]                                             NVARCHAR (50)   NULL,
    [conversion_sign_upsorder_quantity]                                     NVARCHAR (50)   NULL,
    [mobile_conversion_downloadsorder_quantity]                             NVARCHAR (50)   NULL,
    [costs]                                                                 NUMERIC (13, 4) NULL,
    [conversion_downloadsmetric]                                            NVARCHAR (50)   NULL,
    [conversion_purchasesorder_quantity]                                    NVARCHAR (50)   NULL,
    [placement]                                                             NVARCHAR (50)   NULL,
    [account_name]                                                          NVARCHAR (250)  NULL,
    [account_timezone]                                                      NVARCHAR (50)   NULL,
    [card_uri]                                                              NVARCHAR (250)  NULL,
    [conversion_site_visits]                                                NVARCHAR (50)   NULL,
    [conversion_downloads]                                                  NVARCHAR (50)   NULL,
    [tweet]                                                                 NVARCHAR (MAX)  NULL,
    [tweet_id]                                                              BIGINT          NULL,
    [tweet_account]                                                         NVARCHAR (50)   NULL,
    [card_type]                                                             NVARCHAR (50)   NULL,
    [conversion_purchases]                                                  NVARCHAR (50)   NULL,
    [card_name]                                                             NVARCHAR (1500) NULL,
    [tweet_user_id]                                                         NVARCHAR (50)   NULL,
    [conversion_custom]                                                     NVARCHAR (50)   NULL,
    [approval_status]                                                       NVARCHAR (50)   NULL,
    [conversion_sign_ups]                                                   NVARCHAR (50)   NULL,
    [updated_at]                                                            NVARCHAR (50)   NULL,
    [id]                                                                    NVARCHAR (150)  NULL,
    [card_title]                                                            NVARCHAR (1500) NULL,
    [mobile_conversion_logins]                                              NVARCHAR (50)   NULL,
    [card_id]                                                               NVARCHAR (150)  NULL,
    [account_id_ui]                                                         NVARCHAR (150)  NULL,
    [mobile_conversion_lifetime_value_tutorials_completed]                  BIGINT          NULL,
    [mobile_conversion_lifetime_value_add_to_wishlists]                     BIGINT          NULL,
    [mobile_conversion_lifetime_value_achievements_unlocked]                BIGINT          NULL,
    [qualified_impressions]                                                 BIGINT          NULL,
    [campaign_end_time]                                                     DATETIME        NULL,
    [video_3s100pct_views]                                                  BIGINT          NULL,
    [mobile_conversion_content_views]                                       BIGINT          NULL,
    [mobile_conversion_lifetime_value_purchases]                            BIGINT          NULL,
    [mobile_conversion_lifetime_value_add_to_carts]                         BIGINT          NULL,
    [campaign_start_time]                                                   DATETIME        NULL,
    [mobile_conversion_spent_credits]                                       BIGINT          NULL,
    [mobile_conversion_invites]                                             BIGINT          NULL,
    [mobile_conversion_payment_info_additions]                              BIGINT          NULL,
    [mobile_conversion_lifetime_value_updates]                              BIGINT          NULL,
    [mobile_conversion_lifetime_value_spent_credits]                        BIGINT          NULL,
    [mobile_conversion_lifetime_value_payment_info_additions]               BIGINT          NULL,
    [video_content_starts]                                                  BIGINT          NULL,
    [mobile_conversion_tutorials_completed]                                 BIGINT          NULL,
    [video_cta_clicks]                                                      BIGINT          NULL,
    [mobile_conversion_lifetime_value_sign_ups]                             BIGINT          NULL,
    [poll_card_vote]                                                        BIGINT          NULL,
    [video_mrc_views]                                                       BIGINT          NULL,
    [mobile_conversion_lifetime_value_rates]                                BIGINT          NULL,
    [mobile_conversion_add_to_wishlists]                                    BIGINT          NULL,
    [mobile_conversion_reservations_]                                       BIGINT          NULL,
    [mobile_conversion_levels_achieved]                                     BIGINT          NULL,
    [mobile_conversion_lifetime_value_shares]                               BIGINT          NULL,
    [carousel_swipes]                                                       BIGINT          NULL,
    [mobile_conversion_lifetime_value_levels_achieved]                      BIGINT          NULL,
    [video_6s_views]                                                        BIGINT          NULL,
    [mobile_conversion_lifetime_value_checkouts_initiated]                  BIGINT          NULL,
    [billed_charge_local_micro]                                             BIGINT          NULL,
    [mobile_conversion_searches]                                            BIGINT          NULL,
    [campaign_duration_in_days]                                             BIGINT          NULL,
    [mobile_conversion_lifetime_value_reservations]                         BIGINT          NULL,
    [mobile_conversion_installs]                                            BIGINT          NULL,
    [mobile_conversion_rates]                                               BIGINT          NULL,
    [mobile_conversion_achievements_unlocked]                               BIGINT          NULL,
    [mobile_conversion_add_to_carts]                                        BIGINT          NULL,
    [mobile_conversion_updates]                                             BIGINT          NULL,
    [mobile_conversion_re_engages]                                          BIGINT          NULL,
    [mobile_conversion_lifetime_value_invites]                              BIGINT          NULL,
    [mobile_conversion_key_page_views]                                      BIGINT          NULL,
    [mobile_conversion_shares]                                              BIGINT          NULL,
    [campaign_updated_at]                                                   NVARCHAR (50)   NULL,
    [mobile_conversion_checkouts_initiated]                                 BIGINT          NULL,
    [mobile_conversion_lifetime_value_purchasesmetric]                      NVARCHAR (50)   NULL,
    [mobile_conversion_installsassisted]                                    NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_achievements_unlockedorder_quantity]  NVARCHAR (50)   NULL,
    [mobile_conversion_sharesorder_quantity]                                NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_add_to_wishlistsorder_quantity]       NVARCHAR (50)   NULL,
    [mobile_conversion_installspost_engagement]                             NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_purchasesorder_quantity]              NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_cartsassisted]                                NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_updatesmetric]                        NVARCHAR (50)   NULL,
    [mobile_conversion_sharespost_engagement]                               NVARCHAR (50)   NULL,
    [mobile_conversion_searchessale_amount]                                 NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_searchessale_amount]                  NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_wishlistsassisted]                            NVARCHAR (50)   NULL,
    [mobile_conversion_installssale_amount]                                 NVARCHAR (50)   NULL,
    [mobile_conversion_invitesorder_quantity]                               NVARCHAR (50)   NULL,
    [mobile_conversion_checkouts_initiatedassisted]                         NVARCHAR (50)   NULL,
    [mobile_conversion_levels_achievedassisted]                             NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_content_viewsorder_quantity]          NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_searchesmetric]                       NVARCHAR (50)   NULL,
    [mobile_conversion_re_engagesorder_quantity]                            NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_cartspost_view]                               NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_ratessale_amount]                     NVARCHAR (50)   NULL,
    [mobile_conversion_sharessale_amount]                                   NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_tutorials_completedsale_amount]       NVARCHAR (50)   NULL,
    [mobile_conversion_checkouts_initiatedorder_quantity]                   NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_payment_info_additionsorder_quantity] NVARCHAR (50)   NULL,
    [mobile_conversion_invitespost_view]                                    NVARCHAR (50)   NULL,
    [mobile_conversion_updatesorder_quantity]                               NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_levels_achievedsale_amount]           NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_reservationssale_amount]              NVARCHAR (50)   NULL,
    [mobile_conversion_sharespost_view]                                     NVARCHAR (50)   NULL,
    [mobile_conversion_spent_creditsorder_quantity]                         NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_spent_creditssale_amount]             NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_wishlistsorder_quantity]                      NVARCHAR (50)   NULL,
    [mobile_conversion_spent_creditspost_engagement]                        NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_invitesmetric]                        NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_add_to_wishlistsmetric]               NVARCHAR (50)   NULL,
    [mobile_conversion_content_viewspost_view]                              NVARCHAR (50)   NULL,
    [mobile_conversion_payment_info_additionspost_engagement]               NVARCHAR (50)   NULL,
    [mobile_conversion_checkouts_initiatedsale_amount]                      NVARCHAR (50)   NULL,
    [mobile_conversion_ratespost_view]                                      NVARCHAR (50)   NULL,
    [mobile_conversion_achievements_unlockedassisted]                       NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_sign_upsorder_quantity]               NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_updatessale_amount]                   NVARCHAR (50)   NULL,
    [mobile_conversion_levels_achievedsale_amount]                          NVARCHAR (50)   NULL,
    [mobile_conversion_re_engagespost_engagement]                           NVARCHAR (50)   NULL,
    [mobile_conversion_invitesassisted]                                     NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_sharesmetric]                         NVARCHAR (50)   NULL,
    [mobile_conversion_payment_info_additionsassisted]                      NVARCHAR (50)   NULL,
    [mobile_conversion_levels_achievedorder_quantity]                       NVARCHAR (50)   NULL,
    [mobile_conversion_ratesassisted]                                       NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_spent_creditsmetric]                  NVARCHAR (50)   NULL,
    [mobile_conversion_tutorials_completedpost_view]                        NVARCHAR (50)   NULL,
    [mobile_conversion_tutorials_completedassisted]                         NVARCHAR (50)   NULL,
    [mobile_conversion_checkouts_initiatedpost_engagement]                  NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_achievements_unlockedsale_amount]     NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_invitessale_amount]                   NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_reservationsmetric]                   NVARCHAR (50)   NULL,
    [mobile_conversion_spent_creditssale_amount]                            NVARCHAR (50)   NULL,
    [mobile_conversion_spent_creditsassisted]                               NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_achievements_unlockedmetric]          NVARCHAR (50)   NULL,
    [mobile_conversion_updatespost_view]                                    NVARCHAR (50)   NULL,
    [mobile_conversion_updatessale_amount]                                  NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_updatesorder_quantity]                NVARCHAR (50)   NULL,
    [mobile_conversion_content_viewsassisted]                               NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_tutorials_completedorder_quantity]    NVARCHAR (50)   NULL,
    [mobile_conversion_re_engagessale_amount]                               NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_add_to_cartssale_amount]              NVARCHAR (50)   NULL,
    [mobile_conversion_invitessale_amount]                                  NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_wishlistspost_view]                           NVARCHAR (50)   NULL,
    [mobile_conversion_invitespost_engagement]                              NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_levels_achievedmetric]                NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_add_to_cartsmetric]                   NVARCHAR (50)   NULL,
    [mobile_conversion_ratesorder_quantity]                                 NVARCHAR (50)   NULL,
    [mobile_conversion_achievements_unlockedsale_amount]                    NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_spent_creditsorder_quantity]          NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_add_to_wishlistssale_amount]          NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_payment_info_additionssale_amount]    NVARCHAR (50)   NULL,
    [mobile_conversion_ratespost_engagement]                                NVARCHAR (50)   NULL,
    [mobile_conversion_searchespost_engagement]                             NVARCHAR (50)   NULL,
    [mobile_conversion_achievements_unlockedpost_view]                      NVARCHAR (50)   NULL,
    [mobile_conversion_tutorials_completedpost_engagement]                  NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_loginsmetric]                         NVARCHAR (50)   NULL,
    [mobile_conversion_installsorder_quantity]                              NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_checkouts_initiatedorder_quantity]    NVARCHAR (50)   NULL,
    [mobile_conversion_re_engagespost_view]                                 NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_cartspost_engagement]                         NVARCHAR (50)   NULL,
    [mobile_conversion_achievements_unlockedpost_engagement]                NVARCHAR (50)   NULL,
    [mobile_conversion_searchesassisted]                                    NVARCHAR (50)   NULL,
    [mobile_conversion_key_page_viewspost_engagement]                       NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_content_viewsmetric]                  NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_purchasessale_amount]                 NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_add_to_cartsorder_quantity]           NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_loginsorder_quantity]                 NVARCHAR (50)   NULL,
    [mobile_conversion_updatespost_engagement]                              NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_sign_upssale_amount]                  NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_checkouts_initiatedsale_amount]       NVARCHAR (50)   NULL,
    [mobile_conversion_content_viewssale_amount]                            NVARCHAR (50)   NULL,
    [mobile_conversion_searchespost_view]                                   NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_sharessale_amount]                    NVARCHAR (50)   NULL,
    [mobile_conversion_achievements_unlockedorder_quantity]                 NVARCHAR (50)   NULL,
    [mobile_conversion_sharesassisted]                                      NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_ratesorder_quantity]                  NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_checkouts_initiatedmetric]            NVARCHAR (50)   NULL,
    [mobile_conversion_tutorials_completedorder_quantity]                   NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_ratesmetric]                          NVARCHAR (50)   NULL,
    [mobile_conversion_content_viewsorder_quantity]                         NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_tutorials_completedmetric]            NVARCHAR (50)   NULL,
    [mobile_conversion_payment_info_additionspost_view]                     NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_searchesorder_quantity]               NVARCHAR (50)   NULL,
    [mobile_conversion_levels_achievedpost_view]                            NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_loginssale_amount]                    NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_sign_upsmetric]                       NVARCHAR (50)   NULL,
    [mobile_conversion_key_page_viewspost_view]                             NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_reservationsorder_quantity]           NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_cartsorder_quantity]                          NVARCHAR (50)   NULL,
    [mobile_conversion_content_viewspost_engagement]                        NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_content_viewssale_amount]             NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_wishlistssale_amount]                         NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_payment_info_additionsmetric]         NVARCHAR (50)   NULL,
    [mobile_conversion_checkouts_initiatedpost_view]                        NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_sharesorder_quantity]                 NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_invitesorder_quantity]                NVARCHAR (50)   NULL,
    [mobile_conversion_installspost_view]                                   NVARCHAR (50)   NULL,
    [mobile_conversion_lifetime_value_levels_achievedorder_quantity]        NVARCHAR (50)   NULL,
    [mobile_conversion_ratessale_amount]                                    NVARCHAR (50)   NULL,
    [mobile_conversion_payment_info_additionssale_amount]                   NVARCHAR (50)   NULL,
    [mobile_conversion_updatesassisted]                                     NVARCHAR (50)   NULL,
    [mobile_conversion_re_engagesassisted]                                  NVARCHAR (50)   NULL,
    [mobile_conversion_searchesorder_quantity]                              NVARCHAR (50)   NULL,
    [mobile_conversion_spent_creditspost_view]                              NVARCHAR (50)   NULL,
    [mobile_conversion_payment_info_additionsorder_quantity]                NVARCHAR (50)   NULL,
    [mobile_conversion_levels_achievedpost_engagement]                      NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_cartssale_amount]                             NVARCHAR (50)   NULL,
    [mobile_conversion_add_to_wishlistspost_engagement]                     NVARCHAR (50)   NULL,
    [mobile_conversion_tutorials_completedsale_amount]                      NVARCHAR (50)   NULL,
    [date]                                                                  DATE            NULL
);

