CREATE TABLE [dbo].[Nestle_Twitter_Ads_Gender] (
    [dt_created]                DATETIME        NULL,
    [dt_updated]                DATETIME        NULL,
    [dt_filename]               NVARCHAR (255)  NULL,
    [tweet]                     NVARCHAR (MAX)  NULL,
    [segment_value]             NVARCHAR (MAX)  NULL,
    [retweets]                  NVARCHAR (50)   NULL,
    [card_engagements]          NVARCHAR (50)   NULL,
    [video_views_25]            BIGINT          NULL,
    [replies]                   NVARCHAR (50)   NULL,
    [impressions]               BIGINT          NULL,
    [media_engagements]         BIGINT          NULL,
    [video_views_75]            BIGINT          NULL,
    [video_content_starts]      BIGINT          NULL,
    [campaign]                  NVARCHAR (MAX)  NULL,
    [type]                      NVARCHAR (50)   NULL,
    [video_3s100pct_views]      BIGINT          NULL,
    [line_item_id]              NVARCHAR (MAX)  NULL,
    [url_clicks]                BIGINT          NULL,
    [video_total_views]         BIGINT          NULL,
    [line_item_name]            NVARCHAR (MAX)  NULL,
    [billed_engagements]        NVARCHAR (MAX)  NULL,
    [costs]                     NUMERIC (20, 4) NULL,
    [tweet_id]                  BIGINT          NULL,
    [timestamp]                 DATE            NULL,
    [media_views]               BIGINT          NULL,
    [qualified_impressions]     BIGINT          NULL,
    [follows]                   NVARCHAR (50)   NULL,
    [likes]                     BIGINT          NULL,
    [campaign_id]               NVARCHAR (MAX)  NULL,
    [app_clicks]                NVARCHAR (50)   NULL,
    [video_views_100]           BIGINT          NULL,
    [segment_name]              NVARCHAR (MAX)  NULL,
    [video_cta_clicks]          BIGINT          NULL,
    [billed_charge_local_micro] BIGINT          NULL,
    [video_6s_views]            BIGINT          NULL,
    [video_views_50]            BIGINT          NULL,
    [clicks]                    BIGINT          NULL,
    [engagements]               BIGINT          NULL,
    [video_mrc_views]           BIGINT          NULL,
    [placement]                 NVARCHAR (MAX)  NULL,
    [account_id_ui]             NVARCHAR (50)   NULL,
    [account_id]                NVARCHAR (50)   NULL,
    [account_name]              NVARCHAR (MAX)  NULL,
    [account]                   NVARCHAR (MAX)  NULL,
    [account_timezone]          NVARCHAR (50)   NULL,
    [conversion_site_visits]    NVARCHAR (50)   NULL,
    [conversion_downloads]      NVARCHAR (50)   NULL,
    [conversion_purchases]      NVARCHAR (50)   NULL,
    [conversion_custom]         NVARCHAR (50)   NULL,
    [conversion_sign_ups]       NVARCHAR (50)   NULL,
    [date]                      DATE            NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_Nestle_Twitter_Ads_Gender_dt_filename]
    ON [dbo].[Nestle_Twitter_Ads_Gender]([dt_filename] ASC);

