CREATE TABLE [dbo].[Nestle_Pinterest_RT] (
    [Date]                      DATE            NULL,
    [Platform]                  VARCHAR (9)     NULL,
    [Account]                   NVARCHAR (MAX)  NULL,
    [Ad Name]                   NVARCHAR (MAX)  NULL,
    [Ad id]                     BIGINT          NULL,
    [Campaign]                  NVARCHAR (MAX)  NULL,
    [Earned Impressions]        BIGINT          NULL,
    [Impressions]               BIGINT          NULL,
    [Earned Clicks]             NVARCHAR (MAX)  NULL,
    [Clicks]                    BIGINT          NULL,
    [Spend]                     NUMERIC (20, 4) NULL,
    [Engagements]               BIGINT          NULL,
    [Earned Saves]              BIGINT          NULL,
    [Saves]                     NVARCHAR (MAX)  NULL,
    [Video Views - 25%]         BIGINT          NULL,
    [Earned Video Views - 25%]  BIGINT          NULL,
    [Earned Video Views - 50%]  BIGINT          NULL,
    [Video Views - 50%]         BIGINT          NULL,
    [Earned Video Views - 75%]  BIGINT          NULL,
    [Video Views - 75%]         BIGINT          NULL,
    [Earned Video Views - 100%] BIGINT          NULL,
    [Video Views - 100%]        BIGINT          NULL,
    [FilterName]                VARCHAR (38)    NULL,
    [Language]                  VARCHAR (7)     NULL,
    [FilterNameUpdated]         VARCHAR (43)    NULL,
    [Brand]                     NVARCHAR (100)  NULL
);

