CREATE TABLE [dbo].[Nestle_Facebook_Age_and_Gender_RT] (
    [Date]                       DATE             NULL,
    [Platform]                   VARCHAR (18)     NULL,
    [Account]                    NVARCHAR (MAX)   NULL,
    [Adset Name]                 NVARCHAR (MAX)   NULL,
    [Campaign]                   NVARCHAR (400)   NULL,
    [Objective]                  NVARCHAR (MAX)   NULL,
    [Gender]                     NVARCHAR (MAX)   NULL,
    [Age]                        NVARCHAR (MAX)   NULL,
    [Creative Thumbnail URL]     NVARCHAR (MAX)   NULL,
    [Creative Title]             NVARCHAR (MAX)   NULL,
    [Creative Name]              NVARCHAR (MAX)   NULL,
    [Creative Body]              NVARCHAR (MAX)   NULL,
    [Spend]                      NUMERIC (13, 4)  NULL,
    [Website Purchase]           NVARCHAR (MAX)   NULL,
    [Impressions]                BIGINT           NULL,
    [Clicks]                     BIGINT           NULL,
    [Link Clicks]                BIGINT           NULL,
    [Post Engagement]            BIGINT           NULL,
    [Video Plays]                BIGINT           NULL,
    [3 Sec Video Plays]          BIGINT           NULL,
    [Video Views - 25%]          BIGINT           NULL,
    [Video Views - 50%]          BIGINT           NULL,
    [Video Views - 75%]          BIGINT           NULL,
    [Video Views - 100%]         BIGINT           NULL,
    [Conversions]                NUMERIC (13, 4)  NULL,
    [CPA]                        NUMERIC (31, 18) NULL,
    [CPE]                        VARCHAR (8000)   NULL,
    [Language]                   NVARCHAR (128)   NULL,
    [Period]                     VARCHAR (3)      NULL,
    [Buy Type]                   VARCHAR (8000)   NULL,
    [Agency Holding Group]       VARCHAR (8000)   NULL,
    [Decoded Master Brand]       NVARCHAR (200)   NULL,
    [Decoded Range Brand]        NVARCHAR (200)   NULL,
    [Decoded Segment]            NVARCHAR (200)   NULL,
    [Market]                     VARCHAR (8000)   NULL,
    [Decoded Campaign Type]      NVARCHAR (200)   NULL,
    [Decoded Campaign Objective] NVARCHAR (200)   NULL,
    [FilterName]                 VARCHAR (38)     NULL,
    [FilterNameUpdated]          VARCHAR (43)     NULL,
    [Brand]                      NVARCHAR (100)   NULL,
    [Campaign_Year]              VARCHAR (6)      NULL,
    [Convention]                 VARCHAR (3)      NOT NULL
);

