CREATE TABLE [dbo].[Nestle_Programmatic_RT] (
    [Campaign]                   NVARCHAR (450)  NULL,
    [Creative]                   NVARCHAR (450)  NULL,
    [Date]                       DATETIME        NULL,
    [Ad Type]                    NVARCHAR (100)  NULL,
    [Creative Attribution]       NVARCHAR (100)  NULL,
    [Impressions]                BIGINT          NULL,
    [Clicks]                     NUMERIC (23, 4) NULL,
    [Conversions]                NUMERIC (38, 4) NULL,
    [Post Click Conversions]     NUMERIC (13, 4) NULL,
    [Engagements]                BIGINT          NULL,
    [Video Views - 25%]          BIGINT          NULL,
    [Video Views - 50%]          FLOAT (53)      NULL,
    [Video Views - 75%]          BIGINT          NULL,
    [Video Views - 100%]         BIGINT          NULL,
    [True View Views]            BIGINT          NULL,
    [True View View Rate]        NUMERIC (13, 4) NULL,
    [Companion Clicks Video]     BIGINT          NULL,
    [Companion Views Video]      BIGINT          NULL,
    [Spend]                      REAL            NULL,
    [Revenue]                    NUMERIC (38, 4) NULL,
    [FilterName]                 VARCHAR (38)    NULL,
    [Language]                   VARCHAR (7)     NULL,
    [Search Partner]             VARCHAR (24)    NULL,
    [FilterNameUpdated]          VARCHAR (43)    NULL,
    [Brand]                      NVARCHAR (100)  NULL,
    [Placement]                  NVARCHAR (450)  NULL,
    [Placement ID]               BIGINT          NULL,
    [Interactions]               BIGINT          NULL,
    [Video Views]                BIGINT          NULL,
    [Video Plays]                BIGINT          NULL,
    [Budget]                     REAL            NULL,
    [Mashup Clicks]              NUMERIC (13, 4) NULL,
    [Mashup Clicks CPA]          NUMERIC (13, 4) NULL,
    [Detailed Page Views]        NUMERIC (13, 4) NULL,
    [Detailed Page View Rate]    NUMERIC (13, 4) NULL,
    [Add To List]                NUMERIC (13, 4) NULL,
    [Units Sold]                 NUMERIC (13, 4) NULL,
    [Sales]                      NUMERIC (13, 4) NULL,
    [New To Brand Purchases]     NUMERIC (13, 4) NULL,
    [New To Brand Product Sales] NUMERIC (13, 4) NULL,
    [New To Brand Units Sold]    NUMERIC (13, 4) NULL,
    [Campaign_Year]              VARCHAR (6)     NULL,
    [Ad Type Category]           VARCHAR (15)    NULL,
    [Convention]                 VARCHAR (3)     NOT NULL,
    [Campaign2]                  NVARCHAR (454)  NULL,
    [Platform]                   VARCHAR (10)    NOT NULL,
    [Decoded Campaign Objective] NVARCHAR (200)  NULL,
    [Decoded Campaign Type]      NVARCHAR (200)  NULL,
    [Decoded Master Brand]       NVARCHAR (200)  NULL,
    [Decoded Range Brand]        NVARCHAR (200)  NULL,
    [Decoded Segment]            NVARCHAR (200)  NULL
);

