CREATE TABLE [dbo].[Nestle_SelectionMap_NewConv] (
    [Agency Holding Group]           NVARCHAR (200) NULL,
    [Agency Holding Group Code]      NVARCHAR (200) NULL,
    [Master Brand]                   NVARCHAR (200) NULL,
    [Master Brand Code]              NVARCHAR (200) NULL,
    [Range Brand]                    NVARCHAR (200) NULL,
    [Range Brand Code]               NVARCHAR (200) NULL,
    [Segment]                        NVARCHAR (200) NULL,
    [Segment Code]                   NVARCHAR (200) NULL,
    [Market]                         NVARCHAR (200) NULL,
    [Market Code]                    NVARCHAR (200) NULL,
    [Campaign Type]                  NVARCHAR (200) NULL,
    [Campaign Type Code]             NVARCHAR (200) NULL,
    [Campaign Objective]             NVARCHAR (200) NULL,
    [Campaign Objective Code]        NVARCHAR (200) NULL,
    [Sub Channel]                    NVARCHAR (200) NULL,
    [Sub Channel Code]               NVARCHAR (200) NULL,
    [Medium]                         NVARCHAR (200) NULL,
    [Medium Code]                    NVARCHAR (200) NULL,
    [DSP]                            NVARCHAR (200) NULL,
    [DSP Code]                       NVARCHAR (200) NULL,
    [Pricing Model]                  NVARCHAR (200) NULL,
    [Pricing Model Code]             NVARCHAR (200) NULL,
    [KPI Automation]                 NVARCHAR (200) NULL,
    [KPI Automation Code]            NVARCHAR (200) NULL,
    [Buying Tactic]                  NVARCHAR (200) NULL,
    [Buying Tactic Code]             NVARCHAR (200) NULL,
    [Audience Type]                  NVARCHAR (200) NULL,
    [Audience Type Code]             NVARCHAR (200) NULL,
    [Audience Data Type]             NVARCHAR (200) NULL,
    [Audience Data Type Code]        NVARCHAR (200) NULL,
    [DMP Activated Audience]         NVARCHAR (200) NULL,
    [DMP Activated Audience Code]    NVARCHAR (200) NULL,
    [Audience Data Source]           NVARCHAR (200) NULL,
    [Audience Data Source Code]      NVARCHAR (200) NULL,
    [Audience Data Source Type]      NVARCHAR (200) NULL,
    [Audience Data Source Type Code] NVARCHAR (200) NULL,
    [Environment]                    NVARCHAR (200) NULL,
    [Environment Code]               NVARCHAR (200) NULL,
    [Device]                         NVARCHAR (200) NULL,
    [Device Code]                    NVARCHAR (200) NULL,
    [Format]                         NVARCHAR (200) NULL,
    [Format Code]                    NVARCHAR (200) NULL,
    [Destination Type]               NVARCHAR (200) NULL,
    [Destination Type Code]          NVARCHAR (200) NULL,
    [Tracking Ad]                    NVARCHAR (200) NULL,
    [Tracking Ad Code]               NVARCHAR (200) NULL,
    [Language]                       NVARCHAR (200) NULL,
    [Language Code]                  NVARCHAR (200) NULL,
    [Content Origin]                 NVARCHAR (200) NULL,
    [Content Origin Code]            NVARCHAR (200) NULL,
    [Content Personalization]        NVARCHAR (200) NULL,
    [Content Personalization Code]   NVARCHAR (200) NULL,
    [DCO Partner]                    NVARCHAR (200) NULL,
    [DCO Partner Code]               NVARCHAR (200) NULL
);

