CREATE TABLE [dbo].[Nestle_GoogleAds_RT] (
    [Account]                      NVARCHAR (400)  NULL,
    [Ad Group]                     NVARCHAR (MAX)  NULL,
    [All Conversions]              NUMERIC (13, 4) NULL,
    [All Conversions Value]        NUMERIC (13, 4) NULL,
    [Brand]                        NVARCHAR (100)  NULL,
    [Branded_CPC]                  NVARCHAR (50)   NULL,
    [Branded_Impr_Share]           NVARCHAR (50)   NULL,
    [Campaign]                     NVARCHAR (450)  NULL,
    [Clicks]                       BIGINT          NULL,
    [Client Customer Name]         NVARCHAR (400)  NULL,
    [Competitive_CPC]              NVARCHAR (50)   NULL,
    [Competitive_Impr_Share]       NVARCHAR (50)   NULL,
    [Conversions]                  NUMERIC (13, 4) NULL,
    [Cost]                         NUMERIC (13, 4) NULL,
    [Date]                         DATE            NULL,
    [Device]                       NVARCHAR (400)  NULL,
    [FilterName]                   VARCHAR (38)    NULL,
    [FilterNameUpdated]            VARCHAR (43)    NULL,
    [Impressions]                  BIGINT          NULL,
    [Keyword]                      NVARCHAR (400)  NULL,
    [Keyword State]                NVARCHAR (50)   NULL,
    [Labels]                       NVARCHAR (900)  NULL,
    [Language]                     VARCHAR (8000)  NULL,
    [Match Type]                   NVARCHAR (100)  NULL,
    [Network]                      NVARCHAR (100)  NULL,
    [Network With Search Partners] NVARCHAR (400)  NULL,
    [Non_Branded_CPC]              NVARCHAR (50)   NULL,
    [Non_Branded_Impr_Share]       NVARCHAR (50)   NULL,
    [Search Impression Share]      FLOAT (53)      NULL,
    [table]                        VARCHAR (20)    NULL,
    [Targeting]                    VARCHAR (11)    NULL,
    [Audience Detail]              VARCHAR (8000)  NULL,
    [Campaign Free Field]          VARCHAR (8000)  NULL,
    [Campaign ID]                  VARCHAR (8000)  NULL,
    [Campaign Match Type]          VARCHAR (8000)  NULL,
    [Campaign Objective]           VARCHAR (8000)  NULL,
    [Country]                      VARCHAR (8000)  NULL,
    [Decoded Audience Detail]      VARCHAR (21)    NULL,
    [Decoded Campaign Match Type]  VARCHAR (20)    NULL,
    [Decoded Campaign Objective]   NVARCHAR (200)  NULL,
    [Decoded Master Brand]         NVARCHAR (200)  NULL,
    [Decoded Range Brand]          NVARCHAR (200)  NULL,
    [Decoded Sub-Segment/Category] VARCHAR (34)    NULL,
    [Local Segment]                VARCHAR (8000)  NULL,
    [Master Brand]                 VARCHAR (8000)  NULL,
    [Range Brand]                  VARCHAR (8000)  NULL,
    [Search Engine]                VARCHAR (8000)  NULL,
    [Sub-Segment]                  VARCHAR (8000)  NULL,
    [Targeting Type]               VARCHAR (8000)  NULL,
    [Campaign_Year]                VARCHAR (6)     NULL,
    [Campaign2]                    NVARCHAR (454)  NULL,
    [Convention]                   VARCHAR (3)     NOT NULL,
    [Branded_CPC_KPI]              NVARCHAR (50)   NULL,
    [Non_Branded_CPC_KPI]          NVARCHAR (50)   NULL,
    [Non_Branded_Impr_Share_KPI]   NVARCHAR (50)   NULL,
    [Branded_Impr_Share_KPI]       NVARCHAR (50)   NULL,
    [Competitive_CPC_KPI]          NVARCHAR (50)   NULL,
    [Competitive_Impr_Share_KPI]   NVARCHAR (50)   NULL
);

