CREATE TABLE [dbo].[Nestle_Google_Ads] (
    [dt_created]                   DATETIME        NULL,
    [dt_updated]                   DATETIME        NULL,
    [dt_filename]                  NVARCHAR (255)  NULL,
    [client_customer_id]           BIGINT          NULL,
    [client_customer_name]         NVARCHAR (400)  NULL,
    [network_with_search_partners] NVARCHAR (400)  NULL,
    [all_conv]                     NUMERIC (13, 4) NULL,
    [network]                      NVARCHAR (100)  NULL,
    [crossdevice_conv]             NVARCHAR (100)  NULL,
    [video_played_to_25]           FLOAT (53)      NULL,
    [clicks]                       BIGINT          NULL,
    [video_played_to_50]           FLOAT (53)      NULL,
    [client_name]                  NVARCHAR (400)  NULL,
    [video_played_to_100]          FLOAT (53)      NULL,
    [interactions]                 BIGINT          NULL,
    [viewthrough_conv]             BIGINT          NULL,
    [device]                       NVARCHAR (400)  NULL,
    [engagements]                  BIGINT          NULL,
    [day]                          DATE            NULL,
    [video_played_to_75]           FLOAT (53)      NULL,
    [all_conv_value]               NUMERIC (13, 4) NULL,
    [conversions]                  NUMERIC (13, 4) NULL,
    [campaign]                     NVARCHAR (450)  NULL,
    [views]                        BIGINT          NULL,
    [campaign_id]                  BIGINT          NULL,
    [labels]                       VARCHAR (900)   NULL,
    [customer_id]                  BIGINT          NULL,
    [cost]                         NUMERIC (13, 4) NULL,
    [total_conv_value]             NUMERIC (13, 4) NULL,
    [impressions]                  BIGINT          NULL,
    [ctr]                          NUMERIC (13, 4) NULL,
    [click_share]                  NVARCHAR (100)  NULL,
    [cost__conv]                   NVARCHAR (100)  NULL,
    [search_impr_share]            NVARCHAR (100)  NULL,
    [day_of_week]                  NVARCHAR (100)  NULL,
    [label_ids]                    NVARCHAR (100)  NULL,
    [view_rate]                    NVARCHAR (100)  NULL,
    [cost__all_conv]               NVARCHAR (100)  NULL,
    [start_date]                   NVARCHAR (100)  NULL,
    [account]                      NVARCHAR (400)  NULL,
    [end_date]                     NVARCHAR (100)  NULL,
    [month_of_year]                NVARCHAR (100)  NULL,
    [video_plays_25]               NVARCHAR (100)  NULL,
    [video_plays_50]               NVARCHAR (100)  NULL,
    [video_plays_75]               NVARCHAR (100)  NULL,
    [video_plays_100]              NVARCHAR (100)  NULL,
    [tablet_bid_adj]               NVARCHAR (100)  NULL,
    [engagement_rate]              FLOAT (53)      NULL,
    [search_top_is]                NUMERIC (13, 4) NULL,
    [recommended_budget_amount]    NVARCHAR (100)  NULL,
    [month]                        DATE            NULL,
    [week]                         DATE            NULL,
    [time_zone]                    NVARCHAR (100)  NULL,
    [invalid_clicks]               BIGINT          NULL,
    [content_impr_share]           NVARCHAR (100)  NULL,
    [budget_period]                NVARCHAR (100)  NULL,
    [interaction_rate]             FLOAT (53)      NULL,
    [conv_rate]                    FLOAT (53)      NULL,
    [budget]                       NUMERIC (13, 4) NULL,
    [search_exact_match_is]        NVARCHAR (100)  NULL,
    [quarter]                      DATE            NULL,
    [currency]                     NVARCHAR (100)  NULL,
    [year]                         BIGINT          NULL,
    [has_recommended_budget]       BIT             NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_Nestle_Google_Ads_dt_filename]
    ON [dbo].[Nestle_Google_Ads]([dt_filename] ASC);


GO
CREATE NONCLUSTERED INDEX [idx_Cust_Camp_Acc]
    ON [dbo].[Nestle_Google_Ads]([client_customer_name] ASC, [campaign] ASC, [account] ASC);

