CREATE TABLE [dbo].[Temp_Nestle_Prog_AmazonDSP] (
    [Date]                                 DATETIME2 (7)  NOT NULL,
    [Advertiser]                           NVARCHAR (MAX) NULL,
    [Advertiser_ID]                        FLOAT (53)     NOT NULL,
    [Order]                                NVARCHAR (50)  NOT NULL,
    [Order_ID]                             FLOAT (53)     NOT NULL,
    [Line_item]                            NVARCHAR (MAX) NOT NULL,
    [Line_item_ID]                         FLOAT (53)     NOT NULL,
    [Creative]                             NVARCHAR (MAX) NOT NULL,
    [Creative_ID]                          FLOAT (53)     NOT NULL,
    [Creative_type]                        NVARCHAR (50)  NULL,
    [Creative_size]                        NVARCHAR (50)  NULL,
    [Supply_cost]                          FLOAT (53)     NOT NULL,
    [Total_cost]                           FLOAT (53)     NOT NULL,
    [Impressions]                          FLOAT (53)     NOT NULL,
    [eCPM]                                 FLOAT (53)     NULL,
    [Click_throughs]                       FLOAT (53)     NOT NULL,
    [CTR]                                  FLOAT (53)     NULL,
    [eCPC]                                 FLOAT (53)     NULL,
    [Survey_start]                         FLOAT (53)     NOT NULL,
    [Survey_start_views]                   FLOAT (53)     NOT NULL,
    [Mashup_click_to_page]                 FLOAT (53)     NOT NULL,
    [Mashup_click_to_page_clicks]          FLOAT (53)     NOT NULL,
    [Mashup_ATC]                           FLOAT (53)     NOT NULL,
    [Mashup_ATC_views]                     FLOAT (53)     NOT NULL,
    [Mashup_ATC_clicks]                    FLOAT (53)     NOT NULL,
    [Mashup_CC_click]                      FLOAT (53)     NOT NULL,
    [Mashup_CC_click_views]                FLOAT (53)     NOT NULL,
    [Mashup_CC_click_clicks]               FLOAT (53)     NOT NULL,
    [Mashup_CC_click_CPA]                  FLOAT (53)     NULL,
    [DPV]                                  FLOAT (53)     NOT NULL,
    [DPVR]                                 FLOAT (53)     NULL,
    [ATL]                                  FLOAT (53)     NOT NULL,
    [ATL_views]                            FLOAT (53)     NOT NULL,
    [ATL_clicks]                           FLOAT (53)     NOT NULL,
    [Purchases]                            FLOAT (53)     NOT NULL,
    [Purchase_rate]                        FLOAT (53)     NULL,
    [New_to_brand_purchases]               FLOAT (53)     NOT NULL,
    [Units_sold]                           FLOAT (53)     NOT NULL,
    [Sales_CAD]                            FLOAT (53)     NOT NULL,
    [ROAS]                                 FLOAT (53)     NULL,
    [New_to_brand_units_sold]              FLOAT (53)     NOT NULL,
    [New_to_brand_product_sales_CAD]       FLOAT (53)     NOT NULL,
    [Total_DPV]                            FLOAT (53)     NOT NULL,
    [Total_DPVR]                           FLOAT (53)     NULL,
    [Total_purchases]                      FLOAT (53)     NOT NULL,
    [Total_purchase_rate]                  FLOAT (53)     NULL,
    [Total_new_to_brand_purchases]         FLOAT (53)     NOT NULL,
    [Total_units_sold]                     FLOAT (53)     NOT NULL,
    [Total_sales_CAD]                      FLOAT (53)     NOT NULL,
    [Total_ROAS]                           FLOAT (53)     NULL,
    [Total_new_to_brand_units_sold]        FLOAT (53)     NOT NULL,
    [Total_new_to_brand_product_sales_CAD] FLOAT (53)     NOT NULL,
    [dt_created]                           DATETIME       NULL,
    [dt_updated]                           DATETIME       NULL,
    [dt_filename]                          NVARCHAR (255) NULL,
    [day_of_week]                          NVARCHAR (MAX) NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_Nestle_Ams_DSP_dt_filename]
    ON [dbo].[Temp_Nestle_Prog_AmazonDSP]([dt_filename] ASC);

