CREATE TYPE [DataSync].[CD_Google_AdWords_dss_BulkType_86428056-fea2-4062-8e10-5f42d853c559] AS TABLE (
    [dt_created]                 DATETIME        NULL,
    [dt_updated]                 DATETIME        NULL,
    [dt_filename]                NVARCHAR (255)  NULL,
    [client_customer_id]         BIGINT          NOT NULL,
    [client_customer_name]       NVARCHAR (MAX)  NULL,
    [currency]                   NVARCHAR (MAX)  NULL,
    [account]                    NVARCHAR (MAX)  NULL,
    [network]                    NVARCHAR (MAX)  NULL,
    [network_w_search_partners]  NVARCHAR (200)  NOT NULL,
    [all_conv]                   NUMERIC (20, 4) NULL,
    [all_conv_value]             NUMERIC (20, 4) NULL,
    [budget]                     NUMERIC (20, 4) NULL,
    [campaign_id]                BIGINT          NOT NULL,
    [campaign]                   NVARCHAR (MAX)  NULL,
    [clicks]                     BIGINT          NULL,
    [conv_rate]                  FLOAT (53)      NULL,
    [conversions]                NUMERIC (20, 4) NULL,
    [total_conv_value]           NUMERIC (20, 4) NULL,
    [cost]                       NUMERIC (20, 4) NULL,
    [crossdevice_conv]           NVARCHAR (MAX)  NULL,
    [client_name]                NVARCHAR (MAX)  NULL,
    [day]                        DATE            NOT NULL,
    [deviceseg]                  NVARCHAR (200)  NOT NULL,
    [end_date]                   NVARCHAR (MAX)  NULL,
    [engagement_rate]            FLOAT (53)      NULL,
    [engagements]                BIGINT          NULL,
    [customer_id]                BIGINT          NULL,
    [impressions]                BIGINT          NULL,
    [interactions]               BIGINT          NULL,
    [invalid_clicks]             BIGINT          NULL,
    [labels]                     NVARCHAR (MAX)  NULL,
    [search_impr_share]          NVARCHAR (MAX)  NULL,
    [start_date]                 DATE            NULL,
    [video_played_to_100]        FLOAT (53)      NULL,
    [video_played_to_25]         FLOAT (53)      NULL,
    [video_played_to_50]         FLOAT (53)      NULL,
    [video_played_to_75]         FLOAT (53)      NULL,
    [view_rate]                  FLOAT (53)      NULL,
    [views]                      BIGINT          NULL,
    [viewthrough_conv]           BIGINT          NULL,
    [sync_update_peer_timestamp] BIGINT          NULL,
    [sync_update_peer_key]       INT             NULL,
    [sync_create_peer_timestamp] BIGINT          NULL,
    [sync_create_peer_key]       INT             NULL,
    PRIMARY KEY CLUSTERED ([client_customer_id] ASC, [network_w_search_partners] ASC, [campaign_id] ASC, [day] ASC, [deviceseg] ASC));

