
create view [dbo].[CD_GCM_NoSpend_View] as

with dcm_ads as (
select [dt_created]
,[dt_updated]
,[dt_filename]
,[creative_id]
,[date]
,[clickthrough_url]
,[ad_id]
,[campaign_id]
,[advertiser_group]
,[campaign_end_date]
,[placement_end_date]
,[placement_start_date]
,[advertiser]
,[creative]
,[placement_cost_structure]
,[ad]
,[placement_id]
,[site_dcm]
,[advertiser_id]
,[ad_status]
,[ad_type]
,[site_id_dcm]
,[campaign]
,[creative_type]
,[campaign_start_date]
,[clicks]
,[impressions]
,[total_conversions]
,[total_revenue]
,[video_views]
,[video_completions]
,[viewthrough_conversions]
,[viewthrough_revenue]
,[click_rate]
,[companion_clicks]
,[video_companion_clicks]
,[companion_views]
,[video_average_view_time]
,[video_first_quartile_completions]
,[video_fullscreen]
,[video_interaction_rate]
,[fullscreen_video_plays]
,[video_interactions]
,[video_mutes]
,[video_midpoints]
,[video_pauses]
,[video_plays]
,[video_skips]
,[video_replays]
,[video_progress_events]
,[video_unmutes]
,[video_third_quartile_completions]
,[video_stops]
,[video_view_rate]
,[fullscreen_video_completions]
,[downloaded_impressions]
,[fullscreen_impressions]
,[fullscreen_average_view_time]
,[interaction_rate]
,[interactive_impressions]
,[average_interaction_time]
,[total_interaction_time]
,[total_interactions]
,[roadblock_impressions]
,[total_display_time]
,[trueview_views]
,[active_view__measurable_impressions]
,[active_view__viewable_impressions]
,[active_view__fullscreen]
,[active_view__visible_at_completion]
,[active_view__visible_at_first_quartile]
,[active_view__visible_at_midpoint]
,[active_view__visible_at_start]
,[active_view__visible_at_third_quartile]
,[active_view__of_completed_impressions_visible]
,[active_view__play_time_visible]
,[active_view__of_first_quartile_impressions_visible]
,[active_view__of_midpoint_impressions_visible]
,[active_view__of_third_quartile_impressions_visible]
,[active_view_eligible_impressions]
,[active_view_average_viewable_time_seconds]
,[active_view_impression_distribution_viewable]
,[active_view_measurable_impressions]
,isnull(x.[Adjusted Placement Names], g.[placement]) as placement
from [dbo].[CD_Xaxis_GCM_Placement_Fix] x
	 right join [dbo].[CD_GCM_Ads] g on x.[Original Placement Names] = g.placement
)
select a.*, NULL AS [Flight Capped Spend], NUll AS [Flight Budget]
FROM	dcm_ads AS a