
create view [dbo].[CD_Google_SEM_View] as
select	[account],
		[all_conv],
		[all_conv_value],
		[budget],
		[budget_period],
		[campaign],
		[campaign_id],
		NULL AS [click_share],
		[clicks],
		[client_customer_id],
		[client_customer_name],
		[client_name],
		NULL AS [content_impr_share],
		NULL AS [conv_rate],
		[conversions],
		[cost],
		NULL AS [cost__all_conv],
		NULL AS [cost__conv],
		[crossdevice_conv],
		NULL AS [ctr],
		[currency],
		[customer_id],
		[day],
		NULL AS [day_of_week],
		[device],
		[dt_created],
		[dt_filename],
		[dt_updated],
		NULL AS [end_date],
		NULL AS [engagement_rate],
		[engagements],
		NULL AS [has_recommended_budget],
		[impressions],
		[interaction_rate],
		[interactions],
		NULL AS [invalid_clicks],
		NULL AS [label_ids],
		[labels],
		NULL AS [month],
		NULL AS [month_of_year],
		[network],
		[network_with_search_partners],
		NULL AS [quarter],
		NULL AS [recommended_budget_amount],
		NULL AS [search_exact_match_is],
		NULL AS [search_impr_share],
		NULL AS [search_top_is],
		NULL AS[start_date],
		NULL AS [tablet_bid_adj],
		NULL AS [time_zone],
		[total_conv_value],
		[video_played_to_100],
		[video_played_to_25],
		[video_played_to_50],
		[video_played_to_75],
				NULL AS [video_plays_100],
		 		NULL AS [video_plays_25],
				NULL AS [video_plays_50],
				NULL AS [video_plays_75],
				NULL AS [view_rate],
		[views],
		[viewthrough_conv],
				NULL AS [week],
				NULL AS [year],
		NULL as [ad_group],
		NULL as [ad_group_id],
		NULL as [keyword],
		NULL as [keyword_id],
		NULL as [keyword_state],
		NULL as [match_type],
		'CD_Google_Ads' as [table]
from [dbo].[CD_Google_Ads_New]

union all

select	NULL as [account],
		NULL as [all_conv],
		NULL as [all_conv_value],
		NULL as [budget],
		NULL as [budget_period],
		[campaign],
		[campaign_id],
		NULL as [click_share],
		[clicks],
		[client_customer_id],
		[client_customer_name],
		NULL as [client_name],
		NULL as [content_impr_share],
		NULL as [conv_rate],
		[conversions],
		[cost],
		NULL as [cost__all_conv],
		NULL as [cost__conv],
		NULL as [crossdevice_conv],
		NULL as [ctr],
		NULL as [currency],
		[customer_id],
		[day],
		NULL as [day_of_week],
		[device],
		[dt_created],
		[dt_filename],
		[dt_updated],
		NULL as [end_date],
		NULL as [engagement_rate],
		[engagements],
		NULL as [has_recommended_budget],
		[impressions],
		NULL as [interaction_rate],
		[interactions],
		NULL as [invalid_clicks],
		[label_ids],
		[labels],
		NULL as [month],
		NULL as [month_of_year],
		[network],
		[network_with_search_partners],
		NULL as [quarter],
		NULL as [recommended_budget_amount],
		NULL as [search_exact_match_is],
		NULL as [search_impr_share],
		NULL as [search_top_is],
		NULL as [start_date],
		NULL as [tablet_bid_adj],
		[time_zone],
		NULL as [total_conv_value],
		NULL as [video_played_to_100],
		NULL as [video_played_to_25],
		NULL as [video_played_to_50],
		NULL as [video_played_to_75],
		NULL as [video_plays_100],
		NULL as [video_plays_25],
		NULL as [video_plays_50],
		NULL as [video_plays_75],
		[view_rate],
		[views],
		NULL as [viewthrough_conv],
		NULL as [week],
		NULL as [year],
		[ad_group],
		[ad_group_id],
		[keyword],
		[keyword_id],
		[keyword_state],
		[match_type],
		'CD_Google_Ads_KW' as [table]
from [dbo].[CD_Google_Ads_KW]