




CREATE VIEW [dbo].[CD_Social_Facebook_View] 
AS

SELECT
[Date],
[Platform], 
[Account],
[Adset Name], 
[Campaign],
[Objective], 
'N/A' AS [Platform Position], 
'N/A' AS [Published Platform],
[Gender], 
[Age],
[Fiscal],
[Campaign Name Brand], 
[Timing], 
[C], 
[P], 
[E], 
[Campaign Name Language],
[Segment], 
[Buy Type], 
[Campaign Name Platform], 
[Campaign Name Objective],
[Campaign Time range],
'N/A' AS[Offer], 
'N/A' AS[IO Number], 
'N/A' AS[Custom 2],
'N/A' AS [Audience], 
'N/A' AS [Region], 
'N/A' AS [Device], 
'N/A' AS [Ad Placement], 
'N/A' AS [Format],
[Creative Thumbnail URL],
[Creative Image URL],
[Creative Title], 
[Creative Body],
[Spend], 
[Impressions],
[Clicks], 
[Link Clicks], 
[Post Engagement], 
[Video Plays], 
[Video Views], 
[Video Views - 25%], 
[Video Views - 50%], 
[Video Views - 75%], 
[Video Views - 100%], 
[Revenue],
[Offsite Conversion Custom 1], 
[Offsite Conversion Custom 2], 
[Purchase], 
[Page Engagement], 
[Ad Name],
[Date Stop], 
[FilterName], 
[Language],
[Brand],
NULL AS [Start Date],
NULL AS [End Date],
NULL AS [Reach],
NULL AS [Frequency],
NULL AS [Update date],
'Age and Gender' AS [Table]

FROM [dbo].[CD_Facebook_Ads_Age_Gender_View]

UNION ALL 
SELECT
[Date],
[Platform], 
[Account],
[Adset Name], 
[Campaign],
[Objective], 
[Platform Position], 
[Published Platform],
'N/A' AS [Gender], 
'N/A' AS[Age],
[Fiscal],
[Campaign Name Brand], 
[Timing], 
[C], 
[P], 
[E], 
[Campaign Name Language],
[Segment], 
[Buy Type], 
[Campaign Name Platform], 
[Campaign Name Objective],
[Campaign Time range],
'N/A' AS[Offer], 
'N/A' AS[IO Number], 
'N/A' AS[Custom 2],
'N/A' AS [Audience], 
'N/A' AS [Region], 
'N/A' AS [Device], 
'N/A' AS [Ad Placement], 
'N/A' AS [Format],
[Creative Thumbnail URL],
[Creative Image URL],
[Creative Title], 
[Creative Body],
[Spend], 
[Impressions],
[Clicks], 
[Link Clicks], 
[Post Engagement], 
[Video Plays], 
[Video Views], 
[Video Views - 25%], 
[Video Views - 50%], 
[Video Views - 75%], 
[Video Views - 100%], 
[Revenue],
[Offsite Conversion Custom 1], 
[Offsite Conversion Custom 2], 
[Purchase], 
[Page Engagement], 
[Ad Name],
[Date Stop], 
[FilterName], 
[Language],
[Brand],
NULL AS [Start Date],
NULL AS [End Date],
NULL AS [Reach],
NULL AS [Frequency],
NULL AS [Update date],
'Publisher Platform' AS [Table]
FROM [dbo].[CD_Facebook_Ads_Publisher_Platform_View]

UNION ALL 
SELECT
NULL AS [Date],
'Facebook/Instagram' AS [Platform], 
[Account],
NULL AS [Adset Name], 
[Campaign],
NULL AS [Objective], 
'N/A' AS [Platform Position], 
'N/A' AS [Published Platform],
'N/A' AS [Gender], 
'N/A' AS[Age],
[Fiscal],
[Campaign Name Brand], 
[Timing], 
[C], 
[P], 
[E], 
[Campaign Name Language],
[Segment], 
[Buy Type], 
[Campaign Name Platform], 
[Campaign Name Objective],

[Campaign Time range],
'N/A' AS[Offer], 
'N/A' AS[IO Number], 
'N/A' AS[Custom 2],
'N/A' AS [Audience], 
'N/A' AS [Region], 
'N/A' AS [Device], 
'N/A' AS [Ad Placement], 
'N/A' AS [Format],
'N/A' AS [Creative Thumbnail URL],
'N/A' AS [Creative Image URL],
'N/A' AS [Creative Title], 
'N/A' AS [Creative Body],
 [Spend], 
 [Impressions],
NULL AS [Clicks], 
[Link Clicks], 
NULL AS [Post Engagement], 
NULL AS [Video Plays], 
NULL AS [Video Views], 
NULL AS [Video Views - 25%], 
NULL AS [Video Views - 50%], 
NULL AS [Video Views - 75%], 
NULL AS [Video Views - 100%], 
NULL AS [Revenue],
NULL AS [Offsite Conversion Custom 1], 
NULL AS [Offsite Conversion Custom 2], 
NULL AS [Purchase], 
NULL AS[Page Engagement], 
NULL AS [Ad Name],
NULL AS[Date Stop], 
[FilterName], 
[Language],
[Brand],
[Start Date],
[End Date],
[Reach],
[Frequency],
[Update date],
[Table]
FROM [dbo].[CD_Facebook_Ads_Reach_View]